import type { EnemyData, EnemyType } from "../types";

// Enemy data with visual properties
// Categories: academic, campus, ranged, flying, boss, nature, swarm
export const ENEMY_DATA: Record<EnemyType, EnemyData> = {
  // =============================================================================
  // ACADEMIC ENEMIES - Academic progression and milestones
  // =============================================================================
  frosh: {
    name: "Writing Sem",
    hp: 185,
    speed: 0.38,
    bounty: 12,
    armor: 0,
    flying: false,
    troopDamage: 15,
    desc: "The first hurdle. Persistence is key.",
    color: "#4ade80",
    size: 20,
    category: "academic",
    traits: [],
  },
  sophomore: {
    name: "Sophomore Slump",
    hp: 345,
    speed: 0.32,
    bounty: 18,
    armor: 0.1,
    flying: false,
    troopDamage: 32,
    desc: "Heavy and demotivating. Harder to push through.",
    color: "#60a5fa",
    size: 22,
    category: "academic",
    traits: ["armored"],
    abilities: [
      {
        type: "slow",
        name: "Demotivation",
        desc: "Slows troops with crushing despair",
        chance: 0.15,
        duration: 2000,
        intensity: 0.2,
      },
    ],
  },
  junior: {
    name: "Junior Paper",
    hp: 630,
    speed: 0.3,
    bounty: 30,
    armor: 0.2,
    flying: false,
    troopDamage: 48,
    desc: "A significant research obstacle. Requires focus.",
    color: "#c084fc",
    size: 24,
    category: "academic",
    traits: ["armored"],
    abilities: [
      {
        type: "tower_weaken",
        name: "Brain Fog",
        desc: "Clouds the minds of nearby towers, reducing damage",
        chance: 1.0,
        duration: 3000,
        intensity: 0.15,
        radius: 100,
      },
    ],
  },
  senior: {
    name: "Senior Thesis",
    hp: 1050,
    speed: 0.24,
    bounty: 50,
    armor: 0.3,
    flying: false,
    troopDamage: 65,
    desc: "The ultimate academic titan. Slow but massive.",
    color: "#f472b6",
    size: 28,
    category: "academic",
    traits: ["armored", "boss"],
    isBoss: true,
    liveCost: 3,
    abilities: [
      {
        type: "stun",
        name: "Thesis Defense",
        desc: "Stuns defenders with overwhelming knowledge",
        chance: 0.2,
        duration: 1500,
      },
    ],
  },
  gradstudent: {
    name: "Grad School App",
    hp: 1540,
    speed: 0.2,
    bounty: 75,
    armor: 0.3,
    flying: false,
    troopDamage: 85,
    desc: "An exhausting, soul-crushing process.",
    color: "#fb923c",
    size: 30,
    category: "academic",
    traits: ["armored", "boss"],
    isBoss: true,
    liveCost: 4,
    abilities: [
      {
        type: "poison",
        name: "Soul Drain",
        desc: "Inflicts existential dread, dealing damage over time",
        chance: 0.25,
        duration: 4000,
        intensity: 12,
      },
    ],
  },
  professor: {
    name: "Tenured Professor",
    hp: 2420,
    speed: 0.16,
    bounty: 100,
    armor: 0.4,
    flying: false,
    troopDamage: 110,
    desc: "Immutable and deeply entrenched.",
    color: "#ef4444",
    size: 32,
    category: "academic",
    traits: ["armored", "boss", "tower_debuffer"],
    isBoss: true,
    liveCost: 5,
    abilities: [
      {
        type: "tower_slow",
        name: "Bureaucracy",
        desc: "Slows tower attack speed with red tape",
        chance: 1.0,
        duration: 4000,
        intensity: 0.35,
        radius: 120,
      },
      {
        type: "stun",
        name: "Pop Quiz",
        desc: "Surprises and stuns defenders",
        chance: 0.2,
        duration: 1200,
      },
    ],
  },
  dean: {
    name: "Dean of College",
    hp: 3850,
    speed: 0.15,
    bounty: 150,
    armor: 0.45,
    flying: false,
    troopDamage: 140,
    desc: "A massive administrative wall.",
    color: "#a855f7",
    size: 36,
    category: "academic",
    traits: ["armored", "boss", "tower_debuffer"],
    isBoss: true,
    liveCost: 6,
    abilities: [
      {
        type: "tower_disable",
        name: "Administrative Hold",
        desc: "Completely disables a tower temporarily",
        chance: 0.15,
        duration: 3500,
        radius: 100,
        cooldown: 8000,
      },
      {
        type: "slow",
        name: "Paperwork",
        desc: "Buries defenders in forms, slowing them",
        chance: 0.25,
        duration: 3500,
        intensity: 0.45,
      },
    ],
  },
  trustee: {
    name: "Board of Trustees",
    hp: 8250,
    speed: 0.12,
    bounty: 300,
    armor: 0.4,
    flying: false,
    troopDamage: 180,
    desc: "The final authority. Practically immovable.",
    color: "#eab308",
    size: 42,
    category: "boss",
    traits: ["armored", "boss", "tower_debuffer", "aoe_attack"],
    isBoss: true,
    aoeRadius: 90,
    aoeDamage: 110,
    liveCost: 10,
    abilities: [
      {
        type: "tower_weaken",
        name: "Budget Cuts",
        desc: "Slashes tower effectiveness across the board",
        chance: 1.0,
        duration: 5000,
        intensity: 0.3,
        radius: 150,
      },
      {
        type: "burn",
        name: "Fiery Decree",
        desc: "Issues burning mandates that damage over time",
        chance: 0.25,
        duration: 4500,
        intensity: 20,
      },
    ],
  },
  // =============================================================================
  // FLYING ENEMIES
  // =============================================================================
  mascot: {
    name: "Rival Mascot",
    hp: 520,
    speed: 0.53,
    bounty: 60,
    armor: 0,
    flying: true,
    desc: "Flying distraction from other schools. Zooms past without stopping.",
    color: "#22d3d3",
    size: 26,
    category: "flying",
    traits: ["flying", "fast", "breakthrough"],
  },
  // =============================================================================
  // RANGED ENEMIES
  // =============================================================================
  archer: {
    name: "P-Rade Marshall",
    hp: 290,
    speed: 0.3,
    bounty: 25,
    armor: 0.1,
    flying: false,
    isRanged: true,
    range: 220,
    attackSpeed: 2200,
    projectileDamage: 45,
    desc: "Directs traffic and shoots order-enforcing arrows.",
    color: "#10b981",
    size: 22,
    category: "ranged",
    traits: ["ranged"],
  },
  mage: {
    name: "Pre-Med Student",
    hp: 400,
    speed: 0.22,
    bounty: 55,
    armor: 0.15,
    flying: false,
    isRanged: true,
    range: 180,
    attackSpeed: 2800,
    projectileDamage: 80,
    desc: "Throws volatile organic chemistry flasks.",
    color: "#8b5cf6",
    size: 24,
    category: "ranged",
    traits: ["ranged", "magic_resist"],
    abilities: [
      {
        type: "burn",
        name: "Chemical Burn",
        desc: "Volatile chemicals cause burning damage",
        chance: 0.3,
        duration: 3000,
        intensity: 12,
      },
    ],
  },
  catapult: {
    name: "Grad School Application",
    hp: 1100,
    speed: 0.14,
    bounty: 90,
    armor: 0.4,
    flying: false,
    isRanged: true,
    range: 240,
    attackSpeed: 4500,
    projectileDamage: 175,
    desc: "Heavy burdens launched from a distance.",
    color: "#854d0e",
    size: 34,
    category: "ranged",
    traits: ["ranged", "armored", "aoe_attack"],
    aoeRadius: 70,
    aoeDamage: 150,
    liveCost: 2,
  },
  warlock: {
    name: "Job Recruiter",
    hp: 500,
    speed: 0.2,
    bounty: 70,
    armor: 0.2,
    flying: false,
    isRanged: true,
    range: 180,
    attackSpeed: 2400,
    projectileDamage: 100,
    desc: "Promises high salaries while draining your spirit.",
    color: "#4c1d95",
    size: 28,
    category: "ranged",
    traits: ["ranged", "tower_debuffer"],
    abilities: [
      {
        type: "tower_blind",
        name: "False Promises",
        desc: "Distracts towers, reducing their range",
        chance: 1.0,
        duration: 4000,
        intensity: 0.2,
        radius: 100,
      },
      {
        type: "poison",
        name: "Soul Siphon",
        desc: "Drains the life force of defenders",
        chance: 0.15,
        duration: 3000,
        intensity: 10,
      },
    ],
  },
  crossbowman: {
    name: "Eating Club Bouncer",
    hp: 600,
    speed: 0.24,
    bounty: 50,
    armor: 0.35,
    flying: false,
    isRanged: true,
    range: 200,
    attackSpeed: 3500,
    projectileDamage: 95,
    desc: "Armored patrol with high-impact bolts.",
    color: "#78350f",
    size: 24,
    category: "ranged",
    traits: ["ranged", "armored"],
    abilities: [
      {
        type: "stun",
        name: "Heavy Bolt",
        desc: "Powerful bolts stun targets on impact",
        chance: 1.0,
        duration: 800,
      },
    ],
  },
  hexer: {
    name: "Dance Group Auditions",
    hp: 350,
    speed: 0.28,
    bounty: 50,
    armor: 0.1,
    flying: false,
    isRanged: true,
    range: 160,
    attackSpeed: 2000,
    projectileDamage: 60,
    desc: "Hypnotic movements that curse your defenders.",
    color: "#be185d",
    size: 22,
    category: "ranged",
    traits: ["ranged"],
    abilities: [
      {
        type: "slow",
        name: "Hypnotic Dance",
        desc: "Mesmerizing movements slow all nearby defenders",
        chance: 1.0,
        duration: 2500,
        intensity: 0.35,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // FLYING ENEMIES (Continued)
  // =============================================================================
  harpy: {
    name: "Late Meal Rush",
    hp: 380,
    speed: 0.6,
    bounty: 45,
    armor: 0.05,
    flying: true,
    desc: "Swift and chaotic flying hunger. Too fast to engage defenders.",
    color: "#7c3aed",
    size: 24,
    category: "flying",
    traits: ["flying", "fast", "breakthrough"],
    abilities: [
      {
        type: "slow",
        name: "Screech",
        desc: "Piercing cries disorient defenders",
        chance: 1.0,
        duration: 1500,
        intensity: 0.3,
      },
    ],
  },
  wyvern: {
    name: "Tiger Transit Wyvern",
    hp: 1200,
    speed: 0.36,
    bounty: 110,
    armor: 0.3,
    flying: true,
    isRanged: true,
    range: 180,
    attackSpeed: 1800,
    projectileDamage: 60,
    desc: "A massive flying dragon that swoops down to attack defenders.",
    color: "#059669",
    size: 36,
    category: "flying",
    traits: ["flying", "boss", "aoe_attack"],
    isBoss: true,
    aoeRadius: 70,
    aoeDamage: 95,
    targetsTroops: true,
    troopDamage: 70,
    troopAttackSpeed: 1800,
    liveCost: 3,
    abilities: [
      {
        type: "burn",
        name: "Fire Breath",
        desc: "Breathes fire that burns all in its path",
        chance: 0.3,
        duration: 3500,
        intensity: 18,
        radius: 80,
      },
    ],
  },
  specter: {
    name: "Firestone Ghost",
    hp: 700,
    speed: 0.4,
    bounty: 80,
    armor: 0.6,
    flying: true,
    desc: "Faded spirit of an alum. Drains life from defenders.",
    color: "#94a3b8",
    size: 26,
    category: "flying",
    traits: ["flying", "magic_resist", "armored"],
    targetsTroops: true,
    troopDamage: 48,
    troopAttackSpeed: 2000,
    liveCost: 2,
    abilities: [
      {
        type: "tower_slow",
        name: "Haunting Presence",
        desc: "Chilling aura slows nearby tower mechanisms",
        chance: 1.0,
        duration: 3000,
        intensity: 0.25,
        radius: 90,
      },
    ],
  },
  // =============================================================================
  // CAMPUS ENEMIES - Campus life and events
  // =============================================================================
  berserker: {
    name: "Cane Spree Athlete",
    hp: 850,
    speed: 0.5,
    bounty: 65,
    armor: 0,
    flying: false,
    troopDamage: 72,
    desc: "High energy ground unit charging forward.",
    color: "#dc2626",
    size: 26,
    category: "campus",
    traits: ["fast"],
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Tackle",
        desc: "Powerful charges stun defenders on impact",
        chance: 0.25,
        duration: 1200,
      },
    ],
  },
  necromancer: {
    name: "Admissions Officer",
    hp: 900,
    speed: 0.18,
    bounty: 100,
    armor: 0.2,
    flying: false,
    troopDamage: 88,
    desc: "Raises 'rejected' spirits to haunt the path.",
    color: "#1e1b4b",
    size: 30,
    category: "campus",
    traits: ["summoner", "magic_resist"],
    liveCost: 2,
    abilities: [
      {
        type: "poison",
        name: "Rejection Letter",
        desc: "Crushing disappointment deals damage over time",
        chance: 0.3,
        duration: 4500,
        intensity: 15,
      },
    ],
  },
  // =============================================================================
  // BOSS ENEMIES - Major threats
  // =============================================================================
  golem: {
    name: "Nassau Lion",
    hp: 14500,
    speed: 0.09,
    bounty: 450,
    armor: 0.35,
    flying: false,
    troopDamage: 160,
    desc: "The stone guardian itself. Near-infinite HP.",
    color: "#57534e",
    size: 44,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 110,
    aoeDamage: 180,
    liveCost: 10,
    abilities: [
      {
        type: "tower_disable",
        name: "Stone Gaze",
        desc: "Petrifying stare disables towers completely",
        chance: 0.15,
        duration: 4500,
        radius: 130,
        cooldown: 10000,
      },
      {
        type: "stun",
        name: "Ground Pound",
        desc: "Massive tremors stun all nearby defenders",
        chance: 0.25,
        duration: 2500,
        radius: 110,
      },
    ],
  },
  shadow_knight: {
    name: "Alumni Donor",
    hp: 1800,
    speed: 0.22,
    bounty: 120,
    armor: 0.5,
    flying: false,
    troopDamage: 115,
    desc: "A powerful figure backed by immense resources.",
    color: "#18181b",
    size: 32,
    category: "boss",
    traits: ["armored", "boss"],
    isBoss: true,
    liveCost: 3,
    abilities: [
      {
        type: "tower_weaken",
        name: "Endowment Pressure",
        desc: "Financial influence weakens tower effectiveness",
        chance: 1.0,
        duration: 4500,
        intensity: 0.35,
        radius: 110,
      },
      {
        type: "burn",
        name: "Dark Flame",
        desc: "Shadowy fire burns defenders",
        chance: 0.2,
        duration: 3500,
        intensity: 18,
      },
    ],
  },
  // =============================================================================
  // CAMPUS ENEMIES (Continued) - Campus life and events
  // =============================================================================
  cultist: {
    name: "Finals Week Cultist",
    hp: 320,
    speed: 0.4,
    bounty: 22,
    armor: 0.05,
    flying: false,
    troopDamage: 27,
    desc: "Sleep-deprived zealots chanting forbidden study rituals.",
    color: "#7c2d12",
    size: 21,
    category: "campus",
    traits: [],
    abilities: [
      {
        type: "slow",
        name: "Sleep Deprivation Aura",
        desc: "Exhaustion slows nearby defenders",
        chance: 0.15,
        duration: 2000,
        intensity: 0.2,
        radius: 60,
      },
    ],
  },
  plaguebearer: {
    name: "Flu Season Carrier",
    hp: 520,
    speed: 0.25,
    bounty: 40,
    armor: 0.15,
    flying: false,
    troopDamage: 58,
    desc: "Spreads infectious misery wherever it walks. Keep your distance.",
    color: "#65a30d",
    size: 25,
    category: "campus",
    traits: ["aoe_attack"],
    liveCost: 2,
    abilities: [
      {
        type: "poison",
        name: "Contagion",
        desc: "Spreads sickness to nearby defenders",
        chance: 0.35,
        duration: 5500,
        intensity: 10,
        radius: 80,
      },
      {
        type: "slow",
        name: "Fever",
        desc: "Weakens defenders with illness",
        chance: 0.25,
        duration: 3500,
        intensity: 0.3,
      },
    ],
  },
  frostling: {
    name: "Winter Break Ghost",
    hp: 350,
    speed: 0.45,
    bounty: 35,
    armor: 0.1,
    flying: false,
    desc: "The lingering chill of empty campus that phases through defenses.",
    color: "#7dd3fc",
    size: 22,
    category: "campus",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "slow",
        name: "Frost Touch",
        desc: "Chilling attacks slow defenders",
        chance: 1.0,
        duration: 2000,
        intensity: 0.35,
      },
    ],
  },
  infernal: {
    name: "Burnout Demon",
    hp: 1100,
    speed: 0.28,
    bounty: 85,
    armor: 0.25,
    flying: false,
    troopDamage: 95,
    desc: "Forged from the flames of overwork and impossible deadlines.",
    color: "#dc2626",
    size: 30,
    category: "campus",
    traits: ["aoe_attack"],
    liveCost: 2,
    abilities: [
      {
        type: "burn",
        name: "Burnout Flames",
        desc: "Spreads the fire of overwork to all nearby",
        chance: 0.35,
        duration: 4000,
        intensity: 25,
        radius: 85,
      },
      {
        type: "tower_weaken",
        name: "Exhaustion Aura",
        desc: "Nearby towers work less effectively",
        chance: 1.0,
        duration: 3500,
        intensity: 0.25,
        radius: 100,
      },
    ],
  },
  assassin: {
    name: "Curve Wrecker",
    hp: 320,
    speed: 0.7,
    bounty: 45,
    armor: 0,
    flying: false,
    troopDamage: 36,
    desc: "Lightning fast, sprints past defenders without stopping.",
    color: "#1e1b4b",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    liveCost: 2,
    abilities: [
      {
        type: "poison",
        name: "Toxic Excellence",
        desc: "Poison of academic overachievement",
        chance: 0.4,
        duration: 3000,
        intensity: 15,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Environmental/biome creatures
  // =============================================================================
  thornwalker: {
    name: "Ivy Overgrowth",
    hp: 680,
    speed: 0.2,
    bounty: 55,
    armor: 0.35,
    flying: false,
    desc: "Living vegetation consumed by dark magic. Thorns regenerate.",
    color: "#166534",
    size: 28,
    category: "nature",
    traits: ["armored", "regenerating"],
    abilities: [
      {
        type: "poison",
        name: "Thorn Poison",
        desc: "Venomous thorns inflict poison on contact",
        chance: 0.35,
        duration: 4000,
        intensity: 10,
      },
    ],
  },
  // =============================================================================
  // BOSS ENEMIES (Continued) - Major threats
  // =============================================================================
  sandworm: {
    name: "Thesis Devourer",
    hp: 1600,
    speed: 0.16,
    bounty: 95,
    armor: 0.4,
    flying: false,
    desc: "Burrows through the ground, consuming all academic progress.",
    color: "#a16207",
    size: 38,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack"],
    isBoss: true,
    aoeRadius: 100,
    aoeDamage: 135,
    liveCost: 4,
    abilities: [
      {
        type: "stun",
        name: "Emergence",
        desc: "Bursting from the ground stuns all nearby",
        chance: 0.25,
        duration: 1800,
        radius: 110,
      },
    ],
  },
  juggernaut: {
    name: "Endowed Chair",
    hp: 4200,
    speed: 0.1,
    bounty: 200,
    armor: 0.6,
    flying: false,
    desc: "Unstoppable academic authority. Backed by millions in funding.",
    color: "#44403c",
    size: 40,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 95,
    aoeDamage: 150,
    liveCost: 6,
    abilities: [
      {
        type: "tower_disable",
        name: "Tenure Review",
        desc: "Intimidating presence completely shuts down towers",
        chance: 0.15,
        duration: 4000,
        radius: 110,
        cooldown: 12000,
      },
      {
        type: "stun",
        name: "Authority Slam",
        desc: "Overwhelming force stuns all defenders",
        chance: 0.25,
        duration: 2000,
        radius: 100,
      },
    ],
  },
  // =============================================================================
  // FLYING ENEMIES (Continued) - Aerial threats
  // =============================================================================
  banshee: {
    name: "Grade Wailing Spirit",
    hp: 480,
    speed: 0.55,
    bounty: 50,
    armor: 0.45,
    flying: true,
    desc: "Screams of those who saw their final grades. Haunting and fast.",
    color: "#e2e8f0",
    size: 24,
    category: "flying",
    traits: ["flying", "fast", "magic_resist"],
    targetsTroops: true,
    troopDamage: 55,
    troopAttackSpeed: 1500,
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Wail of Despair",
        desc: "Piercing scream stuns all nearby defenders",
        chance: 0.25,
        duration: 1000,
        radius: 70,
      },
      {
        type: "tower_slow",
        name: "Haunting Cry",
        desc: "Mournful cries disrupt tower targeting",
        chance: 1.0,
        duration: 2500,
        intensity: 0.3,
        radius: 80,
      },
    ],
  },
  dragon: {
    name: "Ancient Alumnus",
    hp: 12000,
    speed: 0.12,
    bounty: 500,
    armor: 0.38,
    flying: true,
    isRanged: true,
    range: 240,
    attackSpeed: 2200,
    projectileDamage: 150,
    desc: "A legendary donor from centuries past, returned to judge the worthy.",
    color: "#9f1239",
    size: 48,
    category: "boss",
    traits: ["flying", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 120,
    aoeDamage: 220,
    targetsTroops: true,
    troopDamage: 120,
    troopAttackSpeed: 2200,
    liveCost: 10,
    abilities: [
      {
        type: "burn",
        name: "Legacy Flame",
        desc: "Ancient fire that burns through generations",
        chance: 0.35,
        duration: 5000,
        intensity: 25,
        radius: 100,
      },
      {
        type: "tower_disable",
        name: "Endowment Freeze",
        desc: "Withdraws support, disabling towers completely",
        chance: 0.15,
        duration: 4000,
        radius: 150,
        cooldown: 15000,
      },
      {
        type: "stun",
        name: "Roar of Ages",
        desc: "Deafening roar stuns all in the vicinity",
        chance: 0.2,
        duration: 2500,
        radius: 120,
      },
    ],
  },
  // =============================================================================
  // SWARM ENEMIES - Fast, weak, numerous
  // =============================================================================
  athlete: {
    name: "Varsity Runner",
    hp: 210,
    speed: 0.58,
    bounty: 10,
    armor: 0,
    flying: false,
    troopDamage: 10,
    desc: "Fast and agile, sprinting past troops without stopping.",
    color: "#f97316",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
  },
  // =============================================================================
  // CAMPUS ENEMIES (Regional) - Campus life
  // =============================================================================
  tiger_fan: {
    name: "Tiger Fan",
    hp: 230,
    speed: 0.34,
    bounty: 12,
    armor: 0.15,
    flying: false,
    troopDamage: 25,
    desc: "Diehard fan cheering on the team. Carries a poster sign that provides minor protection.",
    color: "#ef4444",
    size: 22,
    category: "campus",
    traits: ["armored"],
    abilities: [
      {
        type: "slow",
        name: "Go Tigers!",
        desc: "Deafening cheers rattle defender focus",
        chance: 0.15,
        duration: 1500,
        intensity: 0.2,
        radius: 50,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Swamp Region
  // =============================================================================
  bog_creature: {
    name: "Bog Lurker",
    hp: 220,
    speed: 0.28,
    bounty: 14,
    armor: 0.2,
    flying: false,
    troopDamage: 20,
    desc: "Shambling swamp horror covered in toxic muck. Slow but resilient.",
    color: "#365314",
    size: 24,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "poison",
        name: "Toxic Muck",
        desc: "Toxic slime poisons on contact",
        chance: 0.25,
        duration: 3000,
        intensity: 6,
      },
    ],
  },
  will_o_wisp: {
    name: "Will-o'-Wisp",
    hp: 90,
    speed: 0.5,
    bounty: 10,
    armor: 0.4,
    flying: true,
    troopDamage: 16,
    desc: "Malevolent spirit light that phases through defenses.",
    color: "#84cc16",
    size: 18,
    category: "flying",
    traits: ["flying", "fast", "magic_resist", "breakthrough"],
    abilities: [
      {
        type: "tower_blind",
        name: "Mesmerizing Light",
        desc: "Distracting glow reduces tower range",
        chance: 1.0,
        duration: 2500,
        intensity: 0.15,
        radius: 60,
      },
    ],
  },
  swamp_troll: {
    name: "Swamp Troll",
    hp: 450,
    speed: 0.2,
    bounty: 25,
    armor: 0.25,
    flying: false,
    troopDamage: 55,
    desc: "Massive brute covered in parasitic growths. Regenerates slowly.",
    color: "#4d7c0f",
    size: 30,
    category: "nature",
    traits: ["armored", "regenerating"],
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Club Smash",
        desc: "Heavy blows stun defenders",
        chance: 0.2,
        duration: 1200,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Desert Region
  // =============================================================================
  nomad: {
    name: "Desert Nomad",
    hp: 160,
    speed: 0.38,
    bounty: 11,
    armor: 0.1,
    flying: false,
    troopDamage: 17,
    desc: "Cursed wanderer of the endless sands, bound by ancient dark pacts.",
    color: "#a16207",
    size: 22,
    category: "swarm",
    traits: ["fast"],
    abilities: [
      {
        type: "slow" as const,
        name: "Sandstorm Shroud",
        desc: "Kicks up blinding sand that slows nearby defenders",
        chance: 0.2,
        duration: 2500,
        intensity: 0.25,
      },
    ],
  },
  scorpion: {
    name: "Giant Scorpion",
    hp: 280,
    speed: 0.32,
    bounty: 18,
    armor: 0.3,
    flying: false,
    troopDamage: 42,
    desc: "Armored desert predator with venomous stinger. Heavily protected.",
    color: "#78350f",
    size: 26,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "poison",
        name: "Venom Sting",
        desc: "Venomous stinger poisons targets",
        chance: 0.35,
        duration: 4000,
        intensity: 12,
      },
    ],
  },
  scarab: {
    name: "Sacred Scarab",
    hp: 140,
    speed: 0.45,
    bounty: 9,
    armor: 0.15,
    flying: false,
    troopDamage: 18,
    desc: "Cursed beetle that scurries past defenders too quickly to catch.",
    color: "#fbbf24",
    size: 16,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
  },
  // =============================================================================
  // NATURE ENEMIES - Winter Region
  // =============================================================================
  snow_goblin: {
    name: "Frost Goblin",
    hp: 130,
    speed: 0.48,
    bounty: 9,
    armor: 0.05,
    flying: false,
    troopDamage: 18,
    desc: "Mischievous ice creature that dashes past defenders.",
    color: "#93c5fd",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "slow",
        name: "Frost Claws",
        desc: "Freezing claws slow targets",
        chance: 1.0,
        duration: 1500,
        intensity: 0.25,
      },
    ],
  },
  yeti: {
    name: "Mountain Yeti",
    hp: 520,
    speed: 0.18,
    bounty: 30,
    armor: 0.35,
    flying: false,
    troopDamage: 62,
    desc: "Primordial ice titan. Massive, furry, and terrifying.",
    color: "#e0f2fe",
    size: 32,
    category: "nature",
    traits: ["armored", "aoe_attack"],
    aoeRadius: 70,
    aoeDamage: 85,
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Frost Slam",
        desc: "Powerful ice slam stuns nearby defenders",
        chance: 0.25,
        duration: 1800,
        radius: 75,
      },
      {
        type: "slow",
        name: "Chilling Presence",
        desc: "Cold aura slows all nearby",
        chance: 1.0,
        duration: 2500,
        intensity: 0.35,
        radius: 70,
      },
    ],
  },
  ice_witch: {
    name: "Frost Sorceress",
    hp: 200,
    speed: 0.3,
    bounty: 20,
    armor: 0.2,
    flying: false,
    isRanged: true,
    range: 200,
    attackSpeed: 2000,
    projectileDamage: 40,
    desc: "Ancient cryomancer wielding devastating ice magic.",
    color: "#60a5fa",
    size: 24,
    category: "ranged",
    traits: ["ranged", "magic_resist"],
    abilities: [
      {
        type: "slow",
        name: "Ice Bolt",
        desc: "Freezing projectiles slow targets significantly",
        chance: 1.0,
        duration: 2500,
        intensity: 0.4,
      },
      {
        type: "tower_slow",
        name: "Winter's Grasp",
        desc: "Chilling magic slows tower mechanisms",
        chance: 1.0,
        duration: 3000,
        intensity: 0.25,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Volcanic Region
  // =============================================================================
  magma_spawn: {
    name: "Magma Spawn",
    hp: 250,
    speed: 0.26,
    bounty: 16,
    armor: 0.25,
    flying: false,
    desc: "Living lava elemental. Burns anything it touches.",
    color: "#ea580c",
    size: 24,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "burn",
        name: "Molten Touch",
        desc: "Contact with magma causes burning",
        chance: 0.35,
        duration: 3000,
        intensity: 12,
      },
    ],
  },
  fire_imp: {
    name: "Fire Imp",
    hp: 110,
    speed: 0.52,
    bounty: 8,
    armor: 0,
    flying: false,
    troopDamage: 18,
    desc: "Mischievous demon that darts past defenders in a flash of flame.",
    color: "#fb923c",
    size: 18,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "burn",
        name: "Imp Fire",
        desc: "Small but painful flames",
        chance: 0.25,
        duration: 2000,
        intensity: 8,
      },
    ],
  },
  ember_guard: {
    name: "Ember Guard",
    hp: 380,
    speed: 0.25,
    bounty: 22,
    armor: 0.35,
    flying: false,
    desc: "Elite infernal knight forged in volcanic fire. Heavily armored.",
    color: "#c2410c",
    size: 28,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "burn",
        name: "Ember Blade",
        desc: "Flaming weapon causes burning wounds",
        chance: 0.3,
        duration: 3500,
        intensity: 15,
      },
      {
        type: "tower_weaken",
        name: "Heat Shimmer",
        desc: "Intense heat disrupts tower accuracy",
        chance: 1.0,
        duration: 2500,
        intensity: 0.15,
        radius: 70,
      },
    ],
  },
};
