import type { EnemyData, EnemyType, EnemyTrait, EnemyCategory, EnemyAbilityType } from "../types";

// Enemy data with visual properties
// Categories: academic, campus, ranged, flying, boss, nature, swarm
export const ENEMY_DATA: Record<EnemyType, EnemyData> = {
  // =============================================================================
  // ACADEMIC ENEMIES - Academic progression and milestones
  // =============================================================================
  frosh: {
    name: "Writing Sem",
    hp: 185,
    speed: 0.38,
    bounty: 12,
    armor: 0,
    flying: false,
    troopDamage: 15,
    desc: "The first hurdle. Persistence is key.",
    color: "#4ade80",
    size: 20,
    category: "academic",
    traits: [],
  },
  sophomore: {
    name: "Sophomore Slump",
    hp: 345,
    speed: 0.32,
    bounty: 18,
    armor: 0.1,
    flying: false,
    troopDamage: 32,
    desc: "Heavy and demotivating. Harder to push through.",
    color: "#60a5fa",
    size: 22,
    category: "academic",
    traits: ["armored"],
    abilities: [
      {
        type: "slow",
        name: "Demotivation",
        desc: "Slows troops with crushing despair",
        chance: 0.15,
        duration: 2000,
        intensity: 0.2,
      },
    ],
  },
  junior: {
    name: "Junior Paper",
    hp: 630,
    speed: 0.3,
    bounty: 30,
    armor: 0.2,
    flying: false,
    troopDamage: 48,
    desc: "A significant research obstacle. Requires focus.",
    color: "#c084fc",
    size: 24,
    category: "academic",
    traits: ["armored"],
    abilities: [
      {
        type: "tower_weaken",
        name: "Brain Fog",
        desc: "Clouds the minds of nearby towers, reducing damage",
        chance: 1.0,
        duration: 3000,
        intensity: 0.15,
        radius: 100,
      },
    ],
  },
  senior: {
    name: "Senior Thesis",
    hp: 1050,
    speed: 0.24,
    bounty: 50,
    armor: 0.3,
    flying: false,
    troopDamage: 65,
    desc: "The ultimate academic titan. Slow but massive.",
    color: "#f472b6",
    size: 28,
    category: "academic",
    traits: ["armored", "boss"],
    isBoss: true,
    liveCost: 3,
    abilities: [
      {
        type: "stun",
        name: "Thesis Defense",
        desc: "Stuns defenders with overwhelming knowledge",
        chance: 0.2,
        duration: 1500,
      },
    ],
  },
  gradstudent: {
    name: "Grad School App",
    hp: 1540,
    speed: 0.2,
    bounty: 75,
    armor: 0.3,
    flying: false,
    troopDamage: 85,
    desc: "An exhausting, soul-crushing process.",
    color: "#fb923c",
    size: 30,
    category: "academic",
    traits: ["armored", "boss"],
    isBoss: true,
    liveCost: 4,
    abilities: [
      {
        type: "poison",
        name: "Soul Drain",
        desc: "Inflicts existential dread, dealing damage over time",
        chance: 0.25,
        duration: 4000,
        intensity: 12,
      },
    ],
  },
  professor: {
    name: "Tenured Professor",
    hp: 2420,
    speed: 0.16,
    bounty: 100,
    armor: 0.4,
    flying: false,
    troopDamage: 110,
    desc: "Immutable and deeply entrenched.",
    color: "#ef4444",
    size: 32,
    category: "academic",
    traits: ["armored", "boss", "tower_debuffer"],
    isBoss: true,
    liveCost: 5,
    abilities: [
      {
        type: "tower_slow",
        name: "Bureaucracy",
        desc: "Slows tower attack speed with red tape",
        chance: 1.0,
        duration: 4000,
        intensity: 0.35,
        radius: 120,
      },
      {
        type: "stun",
        name: "Pop Quiz",
        desc: "Surprises and stuns defenders",
        chance: 0.2,
        duration: 1200,
      },
    ],
  },
  dean: {
    name: "Dean of College",
    hp: 3850,
    speed: 0.15,
    bounty: 150,
    armor: 0.45,
    flying: false,
    troopDamage: 140,
    desc: "A massive administrative wall.",
    color: "#a855f7",
    size: 36,
    category: "academic",
    traits: ["armored", "boss", "tower_debuffer"],
    isBoss: true,
    liveCost: 6,
    abilities: [
      {
        type: "tower_disable",
        name: "Administrative Hold",
        desc: "Completely disables a tower temporarily",
        chance: 0.15,
        duration: 3500,
        radius: 100,
        cooldown: 8000,
      },
      {
        type: "slow",
        name: "Paperwork",
        desc: "Buries defenders in forms, slowing them",
        chance: 0.25,
        duration: 3500,
        intensity: 0.45,
      },
    ],
  },
  trustee: {
    name: "Board of Trustees",
    hp: 8250,
    speed: 0.12,
    bounty: 300,
    armor: 0.4,
    flying: false,
    troopDamage: 180,
    desc: "The final authority. Practically immovable.",
    color: "#eab308",
    size: 42,
    category: "boss",
    traits: ["armored", "boss", "tower_debuffer", "aoe_attack"],
    isBoss: true,
    aoeRadius: 90,
    aoeDamage: 110,
    liveCost: 10,
    abilities: [
      {
        type: "tower_weaken",
        name: "Budget Cuts",
        desc: "Slashes tower effectiveness across the board",
        chance: 1.0,
        duration: 5000,
        intensity: 0.3,
        radius: 150,
      },
      {
        type: "burn",
        name: "Fiery Decree",
        desc: "Issues burning mandates that damage over time",
        chance: 0.25,
        duration: 4500,
        intensity: 20,
      },
    ],
  },
  // =============================================================================
  // FLYING ENEMIES
  // =============================================================================
  mascot: {
    name: "Rival Mascot",
    hp: 520,
    speed: 0.53,
    bounty: 60,
    armor: 0,
    flying: true,
    desc: "Flying distraction from other schools. Zooms past without stopping.",
    color: "#22d3d3",
    size: 26,
    category: "flying",
    traits: ["flying", "fast", "breakthrough"],
  },
  // =============================================================================
  // RANGED ENEMIES
  // =============================================================================
  archer: {
    name: "P-Rade Marshall",
    hp: 290,
    speed: 0.3,
    bounty: 25,
    armor: 0.1,
    flying: false,
    isRanged: true,
    range: 220,
    attackSpeed: 2200,
    projectileDamage: 45,
    desc: "Directs traffic and shoots order-enforcing arrows.",
    color: "#10b981",
    size: 22,
    category: "ranged",
    traits: ["ranged"],
  },
  mage: {
    name: "Pre-Med Student",
    hp: 400,
    speed: 0.22,
    bounty: 55,
    armor: 0.15,
    flying: false,
    isRanged: true,
    range: 180,
    attackSpeed: 2800,
    projectileDamage: 80,
    desc: "Throws volatile organic chemistry flasks.",
    color: "#8b5cf6",
    size: 24,
    category: "ranged",
    traits: ["ranged", "magic_resist"],
    abilities: [
      {
        type: "burn",
        name: "Chemical Burn",
        desc: "Volatile chemicals cause burning damage",
        chance: 0.3,
        duration: 3000,
        intensity: 12,
      },
    ],
  },
  catapult: {
    name: "Grad School Application",
    hp: 1100,
    speed: 0.14,
    bounty: 90,
    armor: 0.4,
    flying: false,
    isRanged: true,
    range: 240,
    attackSpeed: 4500,
    projectileDamage: 175,
    desc: "Heavy burdens launched from a distance.",
    color: "#854d0e",
    size: 34,
    category: "ranged",
    traits: ["ranged", "armored", "aoe_attack"],
    aoeRadius: 70,
    aoeDamage: 150,
    liveCost: 2,
  },
  warlock: {
    name: "Job Recruiter",
    hp: 500,
    speed: 0.2,
    bounty: 70,
    armor: 0.2,
    flying: false,
    isRanged: true,
    range: 180,
    attackSpeed: 2400,
    projectileDamage: 100,
    desc: "Promises high salaries while draining your spirit.",
    color: "#4c1d95",
    size: 28,
    category: "ranged",
    traits: ["ranged", "tower_debuffer"],
    abilities: [
      {
        type: "tower_blind",
        name: "False Promises",
        desc: "Distracts towers, reducing their range",
        chance: 1.0,
        duration: 4000,
        intensity: 0.2,
        radius: 100,
      },
      {
        type: "poison",
        name: "Soul Siphon",
        desc: "Drains the life force of defenders",
        chance: 0.15,
        duration: 3000,
        intensity: 10,
      },
    ],
  },
  crossbowman: {
    name: "Eating Club Bouncer",
    hp: 600,
    speed: 0.24,
    bounty: 50,
    armor: 0.35,
    flying: false,
    isRanged: true,
    range: 200,
    attackSpeed: 3500,
    projectileDamage: 95,
    desc: "Armored patrol with high-impact bolts.",
    color: "#78350f",
    size: 24,
    category: "ranged",
    traits: ["ranged", "armored"],
    abilities: [
      {
        type: "stun",
        name: "Heavy Bolt",
        desc: "Powerful bolts stun targets on impact",
        chance: 1.0,
        duration: 800,
      },
    ],
  },
  hexer: {
    name: "Dance Group Auditions",
    hp: 350,
    speed: 0.28,
    bounty: 50,
    armor: 0.1,
    flying: false,
    isRanged: true,
    range: 160,
    attackSpeed: 2000,
    projectileDamage: 60,
    desc: "Hypnotic movements that curse your defenders.",
    color: "#be185d",
    size: 22,
    category: "ranged",
    traits: ["ranged"],
    abilities: [
      {
        type: "slow",
        name: "Hypnotic Dance",
        desc: "Mesmerizing movements slow all nearby defenders",
        chance: 1.0,
        duration: 2500,
        intensity: 0.35,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // FLYING ENEMIES (Continued)
  // =============================================================================
  harpy: {
    name: "Late Meal Rush",
    hp: 380,
    speed: 0.6,
    bounty: 45,
    armor: 0.05,
    flying: true,
    desc: "Swift and chaotic flying hunger. Too fast to engage defenders.",
    color: "#7c3aed",
    size: 24,
    category: "flying",
    traits: ["flying", "fast", "breakthrough"],
    abilities: [
      {
        type: "slow",
        name: "Screech",
        desc: "Piercing cries disorient defenders",
        chance: 1.0,
        duration: 1500,
        intensity: 0.3,
      },
    ],
  },
  wyvern: {
    name: "Tiger Transit Wyvern",
    hp: 1200,
    speed: 0.36,
    bounty: 110,
    armor: 0.3,
    flying: true,
    isRanged: true,
    range: 180,
    attackSpeed: 1800,
    projectileDamage: 60,
    desc: "A massive flying dragon that swoops down to attack defenders.",
    color: "#059669",
    size: 36,
    category: "flying",
    traits: ["flying", "boss", "aoe_attack"],
    isBoss: true,
    aoeRadius: 70,
    aoeDamage: 95,
    targetsTroops: true,
    troopDamage: 70,
    troopAttackSpeed: 1800,
    liveCost: 3,
    abilities: [
      {
        type: "burn",
        name: "Fire Breath",
        desc: "Breathes fire that burns all in its path",
        chance: 0.3,
        duration: 3500,
        intensity: 18,
        radius: 80,
      },
    ],
  },
  specter: {
    name: "Firestone Ghost",
    hp: 700,
    speed: 0.4,
    bounty: 80,
    armor: 0.3,
    flying: true,
    desc: "Faded spirit of an alum. Drains life from defenders.",
    color: "#94a3b8",
    size: 26,
    category: "flying",
    traits: ["flying", "magic_resist", "armored"],
    targetsTroops: true,
    troopDamage: 48,
    troopAttackSpeed: 2000,
    liveCost: 2,
    abilities: [
      {
        type: "tower_slow",
        name: "Haunting Presence",
        desc: "Chilling aura slows nearby tower mechanisms",
        chance: 1.0,
        duration: 3000,
        intensity: 0.25,
        radius: 90,
      },
    ],
  },
  // =============================================================================
  // CAMPUS ENEMIES - Campus life and events
  // =============================================================================
  berserker: {
    name: "Cane Spree Athlete",
    hp: 850,
    speed: 0.5,
    bounty: 65,
    armor: 0,
    flying: false,
    troopDamage: 72,
    desc: "High energy ground unit charging forward.",
    color: "#dc2626",
    size: 26,
    category: "campus",
    traits: ["fast"],
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Tackle",
        desc: "Powerful charges stun defenders on impact",
        chance: 0.25,
        duration: 1200,
      },
    ],
  },
  necromancer: {
    name: "Admissions Officer",
    hp: 900,
    speed: 0.18,
    bounty: 100,
    armor: 0.2,
    flying: false,
    troopDamage: 88,
    desc: "Raises 'rejected' spirits to haunt the path.",
    color: "#1e1b4b",
    size: 30,
    category: "campus",
    traits: ["summoner", "magic_resist"],
    liveCost: 2,
    summonType: "specter",
    abilities: [
      {
        type: "poison",
        name: "Rejection Letter",
        desc: "Crushing disappointment deals damage over time",
        chance: 0.3,
        duration: 4500,
        intensity: 15,
      },
    ],
  },
  // =============================================================================
  // BOSS ENEMIES - Major threats
  // =============================================================================
  golem: {
    name: "Nassau Lion",
    hp: 14500,
    speed: 0.09,
    bounty: 450,
    armor: 0.35,
    flying: false,
    troopDamage: 160,
    desc: "The stone guardian itself. Near-infinite HP.",
    color: "#57534e",
    size: 44,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 110,
    aoeDamage: 180,
    liveCost: 10,
    abilities: [
      {
        type: "tower_disable",
        name: "Stone Gaze",
        desc: "Petrifying stare disables towers completely",
        chance: 0.15,
        duration: 4500,
        radius: 130,
        cooldown: 10000,
      },
      {
        type: "stun",
        name: "Ground Pound",
        desc: "Massive tremors stun all nearby defenders",
        chance: 0.25,
        duration: 2500,
        radius: 110,
      },
    ],
  },
  shadow_knight: {
    name: "Alumni Donor",
    hp: 1800,
    speed: 0.22,
    bounty: 120,
    armor: 0.5,
    flying: false,
    troopDamage: 115,
    desc: "A powerful figure backed by immense resources.",
    color: "#18181b",
    size: 32,
    category: "boss",
    traits: ["armored", "boss"],
    isBoss: true,
    liveCost: 3,
    abilities: [
      {
        type: "tower_weaken",
        name: "Endowment Pressure",
        desc: "Financial influence weakens tower effectiveness",
        chance: 1.0,
        duration: 4500,
        intensity: 0.35,
        radius: 110,
      },
      {
        type: "burn",
        name: "Dark Flame",
        desc: "Shadowy fire burns defenders",
        chance: 0.2,
        duration: 3500,
        intensity: 18,
      },
    ],
  },
  // =============================================================================
  // CAMPUS ENEMIES (Continued) - Campus life and events
  // =============================================================================
  cultist: {
    name: "Finals Week Cultist",
    hp: 320,
    speed: 0.4,
    bounty: 22,
    armor: 0.05,
    flying: false,
    troopDamage: 27,
    desc: "Sleep-deprived zealots chanting forbidden study rituals.",
    color: "#7c2d12",
    size: 21,
    category: "campus",
    traits: [],
    abilities: [
      {
        type: "slow",
        name: "Sleep Deprivation Aura",
        desc: "Exhaustion slows nearby defenders",
        chance: 0.15,
        duration: 2000,
        intensity: 0.2,
        radius: 60,
      },
    ],
  },
  plaguebearer: {
    name: "Flu Season Carrier",
    hp: 520,
    speed: 0.25,
    bounty: 40,
    armor: 0.15,
    flying: false,
    troopDamage: 58,
    desc: "Spreads infectious misery wherever it walks. Keep your distance.",
    color: "#65a30d",
    size: 25,
    category: "campus",
    traits: ["aoe_attack"],
    liveCost: 2,
    abilities: [
      {
        type: "poison",
        name: "Contagion",
        desc: "Spreads sickness to nearby defenders",
        chance: 0.35,
        duration: 5500,
        intensity: 10,
        radius: 80,
      },
      {
        type: "slow",
        name: "Fever",
        desc: "Weakens defenders with illness",
        chance: 0.25,
        duration: 3500,
        intensity: 0.3,
      },
    ],
  },
  frostling: {
    name: "Winter Break Ghost",
    hp: 350,
    speed: 0.45,
    bounty: 35,
    armor: 0.1,
    flying: false,
    desc: "The lingering chill of empty campus that phases through defenses.",
    color: "#7dd3fc",
    size: 22,
    category: "campus",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "slow",
        name: "Frost Touch",
        desc: "Chilling attacks slow defenders",
        chance: 1.0,
        duration: 2000,
        intensity: 0.35,
      },
    ],
  },
  infernal: {
    name: "Burnout Demon",
    hp: 1100,
    speed: 0.28,
    bounty: 85,
    armor: 0.25,
    flying: false,
    troopDamage: 95,
    desc: "Forged from the flames of overwork and impossible deadlines.",
    color: "#dc2626",
    size: 30,
    category: "campus",
    traits: ["aoe_attack"],
    liveCost: 2,
    abilities: [
      {
        type: "burn",
        name: "Burnout Flames",
        desc: "Spreads the fire of overwork to all nearby",
        chance: 0.35,
        duration: 4000,
        intensity: 25,
        radius: 85,
      },
      {
        type: "tower_weaken",
        name: "Exhaustion Aura",
        desc: "Nearby towers work less effectively",
        chance: 1.0,
        duration: 3500,
        intensity: 0.25,
        radius: 100,
      },
    ],
  },
  assassin: {
    name: "Curve Wrecker",
    hp: 320,
    speed: 0.7,
    bounty: 45,
    armor: 0,
    flying: false,
    troopDamage: 36,
    desc: "Lightning fast, sprints past defenders without stopping.",
    color: "#1e1b4b",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    liveCost: 2,
    abilities: [
      {
        type: "poison",
        name: "Toxic Excellence",
        desc: "Poison of academic overachievement",
        chance: 0.4,
        duration: 3000,
        intensity: 15,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Environmental/biome creatures
  // =============================================================================
  thornwalker: {
    name: "Ivy Overgrowth",
    hp: 680,
    speed: 0.2,
    bounty: 55,
    armor: 0.35,
    flying: false,
    desc: "Living vegetation consumed by dark magic. Thorns regenerate.",
    color: "#166534",
    size: 28,
    category: "nature",
    traits: ["armored", "regenerating"],
    abilities: [
      {
        type: "poison",
        name: "Thorn Poison",
        desc: "Venomous thorns inflict poison on contact",
        chance: 0.35,
        duration: 4000,
        intensity: 10,
      },
    ],
  },
  // =============================================================================
  // BOSS ENEMIES (Continued) - Major threats
  // =============================================================================
  sandworm: {
    name: "Thesis Devourer",
    hp: 1600,
    speed: 0.16,
    bounty: 95,
    armor: 0.4,
    flying: false,
    desc: "Burrows through the ground, consuming all academic progress.",
    color: "#a16207",
    size: 38,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack"],
    isBoss: true,
    aoeRadius: 100,
    aoeDamage: 135,
    liveCost: 4,
    abilities: [
      {
        type: "stun",
        name: "Emergence",
        desc: "Bursting from the ground stuns all nearby",
        chance: 0.25,
        duration: 1800,
        radius: 110,
      },
    ],
  },
  juggernaut: {
    name: "Endowed Chair",
    hp: 4200,
    speed: 0.1,
    bounty: 200,
    armor: 0.6,
    flying: false,
    desc: "Unstoppable academic authority. Backed by millions in funding.",
    color: "#44403c",
    size: 40,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 95,
    aoeDamage: 150,
    liveCost: 6,
    abilities: [
      {
        type: "tower_disable",
        name: "Tenure Review",
        desc: "Intimidating presence completely shuts down towers",
        chance: 0.15,
        duration: 4000,
        radius: 110,
        cooldown: 12000,
      },
      {
        type: "stun",
        name: "Authority Slam",
        desc: "Overwhelming force stuns all defenders",
        chance: 0.25,
        duration: 2000,
        radius: 100,
      },
    ],
  },
  // =============================================================================
  // FLYING ENEMIES (Continued) - Aerial threats
  // =============================================================================
  banshee: {
    name: "Grade Wailing Spirit",
    hp: 480,
    speed: 0.55,
    bounty: 50,
    armor: 0.45,
    flying: true,
    desc: "Screams of those who saw their final grades. Haunting and fast.",
    color: "#e2e8f0",
    size: 24,
    category: "flying",
    traits: ["flying", "fast", "magic_resist"],
    targetsTroops: true,
    troopDamage: 55,
    troopAttackSpeed: 1500,
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Wail of Despair",
        desc: "Piercing scream stuns all nearby defenders",
        chance: 0.25,
        duration: 1000,
        radius: 70,
      },
      {
        type: "tower_slow",
        name: "Haunting Cry",
        desc: "Mournful cries disrupt tower targeting",
        chance: 1.0,
        duration: 2500,
        intensity: 0.3,
        radius: 80,
      },
    ],
  },
  dragon: {
    name: "Ancient Alumnus",
    hp: 12000,
    speed: 0.12,
    bounty: 500,
    armor: 0.38,
    flying: true,
    isRanged: true,
    range: 240,
    attackSpeed: 2200,
    projectileDamage: 150,
    desc: "A legendary donor from centuries past, returned to judge the worthy.",
    color: "#9f1239",
    size: 48,
    category: "boss",
    traits: ["flying", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 120,
    aoeDamage: 220,
    targetsTroops: true,
    troopDamage: 120,
    troopAttackSpeed: 2200,
    liveCost: 10,
    abilities: [
      {
        type: "burn",
        name: "Legacy Flame",
        desc: "Ancient fire that burns through generations",
        chance: 0.35,
        duration: 5000,
        intensity: 25,
        radius: 100,
      },
      {
        type: "tower_disable",
        name: "Endowment Freeze",
        desc: "Withdraws support, disabling towers completely",
        chance: 0.15,
        duration: 4000,
        radius: 150,
        cooldown: 15000,
      },
      {
        type: "stun",
        name: "Roar of Ages",
        desc: "Deafening roar stuns all in the vicinity",
        chance: 0.2,
        duration: 2500,
        radius: 120,
      },
    ],
  },
  // =============================================================================
  // SWARM ENEMIES - Fast, weak, numerous
  // =============================================================================
  athlete: {
    name: "Varsity Runner",
    hp: 210,
    speed: 0.58,
    bounty: 10,
    armor: 0,
    flying: false,
    troopDamage: 10,
    desc: "Fast and agile, sprinting past troops without stopping.",
    color: "#f97316",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
  },
  // =============================================================================
  // CAMPUS ENEMIES (Regional) - Campus life
  // =============================================================================
  tiger_fan: {
    name: "Tiger Fan",
    hp: 230,
    speed: 0.34,
    bounty: 12,
    armor: 0.15,
    flying: false,
    troopDamage: 25,
    desc: "Diehard fan cheering on the team. Carries a poster sign that provides minor protection.",
    color: "#ef4444",
    size: 22,
    category: "campus",
    traits: ["armored"],
    abilities: [
      {
        type: "slow",
        name: "Go Tigers!",
        desc: "Deafening cheers rattle defender focus",
        chance: 0.15,
        duration: 1500,
        intensity: 0.2,
        radius: 50,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Swamp Region
  // =============================================================================
  bog_creature: {
    name: "Bog Lurker",
    hp: 220,
    speed: 0.28,
    bounty: 14,
    armor: 0.2,
    flying: false,
    troopDamage: 20,
    desc: "Shambling swamp horror covered in toxic muck. Slow but resilient.",
    color: "#365314",
    size: 24,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "poison",
        name: "Toxic Muck",
        desc: "Toxic slime poisons on contact",
        chance: 0.25,
        duration: 3000,
        intensity: 6,
      },
    ],
  },
  will_o_wisp: {
    name: "Will-o'-Wisp",
    hp: 90,
    speed: 0.5,
    bounty: 10,
    armor: 0.4,
    flying: true,
    troopDamage: 16,
    desc: "Malevolent spirit light that phases through defenses.",
    color: "#84cc16",
    size: 18,
    category: "flying",
    traits: ["flying", "fast", "magic_resist", "breakthrough"],
    abilities: [
      {
        type: "tower_blind",
        name: "Mesmerizing Light",
        desc: "Distracting glow reduces tower range",
        chance: 1.0,
        duration: 2500,
        intensity: 0.15,
        radius: 60,
      },
    ],
  },
  swamp_troll: {
    name: "Swamp Troll",
    hp: 450,
    speed: 0.2,
    bounty: 25,
    armor: 0.25,
    flying: false,
    troopDamage: 55,
    desc: "Massive brute covered in parasitic growths. Regenerates slowly.",
    color: "#4d7c0f",
    size: 30,
    category: "nature",
    traits: ["armored", "regenerating"],
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Club Smash",
        desc: "Heavy blows stun defenders",
        chance: 0.2,
        duration: 1200,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Desert Region
  // =============================================================================
  nomad: {
    name: "Desert Nomad",
    hp: 160,
    speed: 0.38,
    bounty: 11,
    armor: 0.1,
    flying: false,
    troopDamage: 17,
    desc: "Cursed wanderer of the endless sands, bound by ancient dark pacts.",
    color: "#a16207",
    size: 22,
    category: "swarm",
    traits: ["fast"],
    abilities: [
      {
        type: "slow" as const,
        name: "Sandstorm Shroud",
        desc: "Kicks up blinding sand that slows nearby defenders",
        chance: 0.2,
        duration: 2500,
        intensity: 0.25,
      },
    ],
  },
  scorpion: {
    name: "Giant Scorpion",
    hp: 280,
    speed: 0.32,
    bounty: 18,
    armor: 0.3,
    flying: false,
    troopDamage: 42,
    desc: "Armored desert predator with venomous stinger. Heavily protected.",
    color: "#78350f",
    size: 26,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "poison",
        name: "Venom Sting",
        desc: "Venomous stinger poisons targets",
        chance: 0.35,
        duration: 4000,
        intensity: 12,
      },
    ],
  },
  scarab: {
    name: "Sacred Scarab",
    hp: 140,
    speed: 0.45,
    bounty: 9,
    armor: 0.15,
    flying: false,
    troopDamage: 18,
    desc: "Cursed beetle that scurries past defenders too quickly to catch.",
    color: "#fbbf24",
    size: 16,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
  },
  // =============================================================================
  // NATURE ENEMIES - Winter Region
  // =============================================================================
  snow_goblin: {
    name: "Frost Goblin",
    hp: 130,
    speed: 0.48,
    bounty: 9,
    armor: 0.05,
    flying: false,
    troopDamage: 18,
    desc: "Mischievous ice creature that dashes past defenders.",
    color: "#93c5fd",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "slow",
        name: "Frost Claws",
        desc: "Freezing claws slow targets",
        chance: 1.0,
        duration: 1500,
        intensity: 0.25,
      },
    ],
  },
  yeti: {
    name: "Mountain Yeti",
    hp: 520,
    speed: 0.18,
    bounty: 30,
    armor: 0.35,
    flying: false,
    troopDamage: 62,
    desc: "Primordial ice titan. Massive, furry, and terrifying.",
    color: "#e0f2fe",
    size: 32,
    category: "nature",
    traits: ["armored", "aoe_attack"],
    aoeRadius: 70,
    aoeDamage: 85,
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Frost Slam",
        desc: "Powerful ice slam stuns nearby defenders",
        chance: 0.25,
        duration: 1800,
        radius: 75,
      },
      {
        type: "slow",
        name: "Chilling Presence",
        desc: "Cold aura slows all nearby",
        chance: 1.0,
        duration: 2500,
        intensity: 0.35,
        radius: 70,
      },
    ],
  },
  ice_witch: {
    name: "Frost Sorceress",
    hp: 200,
    speed: 0.3,
    bounty: 20,
    armor: 0.2,
    flying: false,
    isRanged: true,
    range: 200,
    attackSpeed: 2000,
    projectileDamage: 40,
    desc: "Ancient cryomancer wielding devastating ice magic.",
    color: "#60a5fa",
    size: 24,
    category: "ranged",
    traits: ["ranged", "magic_resist"],
    abilities: [
      {
        type: "slow",
        name: "Ice Bolt",
        desc: "Freezing projectiles slow targets significantly",
        chance: 1.0,
        duration: 2500,
        intensity: 0.4,
      },
      {
        type: "tower_slow",
        name: "Winter's Grasp",
        desc: "Chilling magic slows tower mechanisms",
        chance: 1.0,
        duration: 3000,
        intensity: 0.25,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // NATURE ENEMIES - Volcanic Region
  // =============================================================================
  magma_spawn: {
    name: "Magma Spawn",
    hp: 250,
    speed: 0.26,
    bounty: 16,
    armor: 0.25,
    flying: false,
    desc: "Living lava elemental. Burns anything it touches.",
    color: "#ea580c",
    size: 24,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "burn",
        name: "Molten Touch",
        desc: "Contact with magma causes burning",
        chance: 0.35,
        duration: 3000,
        intensity: 12,
      },
    ],
  },
  fire_imp: {
    name: "Fire Imp",
    hp: 110,
    speed: 0.52,
    bounty: 8,
    armor: 0,
    flying: false,
    troopDamage: 18,
    desc: "Mischievous demon that darts past defenders in a flash of flame.",
    color: "#fb923c",
    size: 18,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "burn",
        name: "Imp Fire",
        desc: "Small but painful flames",
        chance: 0.25,
        duration: 2000,
        intensity: 8,
      },
    ],
  },
  ember_guard: {
    name: "Ember Guard",
    hp: 380,
    speed: 0.25,
    bounty: 22,
    armor: 0.35,
    flying: false,
    desc: "Elite infernal knight forged in volcanic fire. Heavily armored.",
    color: "#c2410c",
    size: 28,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "burn",
        name: "Ember Blade",
        desc: "Flaming weapon causes burning wounds",
        chance: 0.3,
        duration: 3500,
        intensity: 15,
      },
      {
        type: "tower_weaken",
        name: "Heat Shimmer",
        desc: "Intense heat disrupts tower accuracy",
        chance: 1.0,
        duration: 2500,
        intensity: 0.15,
        radius: 70,
      },
    ],
  },
  // =============================================================================
  // BUG ENEMIES - Grassland Region
  // =============================================================================
  orb_weaver: {
    name: "Orb Weaver Spider",
    hp: 320,
    speed: 0.28,
    bounty: 20,
    armor: 0.15,
    flying: false,
    troopDamage: 38,
    desc: "Massive spider that cocoons defenders in paralyzing silk. Spins webs that slow everything nearby.",
    color: "#4a3728",
    size: 28,
    category: "nature",
    traits: ["tower_debuffer"],
    abilities: [
      {
        type: "stun",
        name: "Silk Cocoon",
        desc: "Wraps a defender in sticky silk, immobilizing them",
        chance: 0.25,
        duration: 3000,
        cooldown: 8000,
      },
      {
        type: "tower_slow",
        name: "Web Trap",
        desc: "Leaves webs that slow tower attack speed",
        chance: 1.0,
        duration: 4000,
        intensity: 0.3,
        radius: 60,
      },
    ],
  },
  mantis: {
    name: "Praying Mantis",
    hp: 240,
    speed: 0.42,
    bounty: 16,
    armor: 0.1,
    flying: false,
    troopDamage: 55,
    desc: "Lightning-fast ambush predator with scythe-like forelegs. Strikes before you see it.",
    color: "#65a30d",
    size: 24,
    category: "nature",
    traits: ["fast"],
    abilities: [
      {
        type: "stun",
        name: "Ambush Strike",
        desc: "Lightning strike stuns the target momentarily",
        chance: 0.3,
        duration: 1500,
      },
    ],
  },
  bombardier_beetle: {
    name: "Bombardier Beetle",
    hp: 260,
    speed: 0.3,
    bounty: 17,
    armor: 0.35,
    flying: false,
    isRanged: true,
    range: 140,
    attackSpeed: 2500,
    projectileDamage: 30,
    desc: "Heavily armored beetle that launches boiling acid sprays at defenders.",
    color: "#1e3a5f",
    size: 22,
    category: "nature",
    traits: ["armored", "ranged"],
    abilities: [
      {
        type: "burn",
        name: "Acid Spray",
        desc: "Superheated chemical spray burns targets",
        chance: 0.4,
        duration: 3000,
        intensity: 10,
        radius: 50,
      },
    ],
  },
  // =============================================================================
  // BUG ENEMIES - Swamp Region
  // =============================================================================
  mosquito: {
    name: "Giant Mosquito",
    hp: 150,
    speed: 0.5,
    bounty: 10,
    armor: 0,
    flying: true,
    troopDamage: 20,
    desc: "Bloated bloodsucker that drains life force. Heals itself with each bite.",
    color: "#6b2142",
    size: 20,
    category: "nature",
    traits: ["flying", "fast"],
    abilities: [
      {
        type: "poison",
        name: "Blood Drain",
        desc: "Drains blood, poisoning the target and healing itself",
        chance: 0.35,
        duration: 3000,
        intensity: 8,
      },
    ],
  },
  centipede: {
    name: "Marsh Centipede",
    hp: 400,
    speed: 0.24,
    bounty: 22,
    armor: 0.4,
    flying: false,
    troopDamage: 45,
    desc: "Heavily armored multi-segmented predator. Each segment carries deadly venom glands.",
    color: "#7c2d12",
    size: 30,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "poison",
        name: "Centipede Venom",
        desc: "Injects paralyzing venom with every leg strike",
        chance: 0.4,
        duration: 4000,
        intensity: 14,
      },
      {
        type: "slow",
        name: "Coiling Grip",
        desc: "Wraps around targets, reducing their speed",
        chance: 0.2,
        duration: 2500,
        intensity: 0.35,
      },
    ],
  },
  dragonfly: {
    name: "Swamp Dragonfly",
    hp: 120,
    speed: 0.6,
    bounty: 8,
    armor: 0,
    flying: true,
    troopDamage: 15,
    desc: "Iridescent predator that darts through the air too fast to track.",
    color: "#0ea5e9",
    size: 18,
    category: "swarm",
    traits: ["flying", "fast", "breakthrough"],
    breakthrough: true,
  },
  silk_moth: {
    name: "Phantom Moth",
    hp: 200,
    speed: 0.35,
    bounty: 14,
    armor: 0.05,
    flying: true,
    desc: "Spectral moth whose wing dust blinds tower targeting systems.",
    color: "#c4b5fd",
    size: 22,
    category: "nature",
    traits: ["flying", "tower_debuffer"],
    abilities: [
      {
        type: "tower_blind",
        name: "Blinding Scales",
        desc: "Releases shimmering scales that reduce tower range",
        chance: 1.0,
        duration: 3500,
        intensity: 0.3,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // BUG ENEMIES - Desert Region
  // =============================================================================
  ant_soldier: {
    name: "Sand Ant Soldier",
    hp: 350,
    speed: 0.3,
    bounty: 20,
    armor: 0.25,
    flying: false,
    troopDamage: 40,
    desc: "Elite soldier of a vast desert colony. Summons reinforcements from underground tunnels.",
    color: "#92400e",
    size: 24,
    category: "nature",
    traits: ["armored", "summoner"],
    summonType: "scarab",
    summonCount: 2,
    abilities: [
      {
        type: "stun",
        name: "Mandible Crush",
        desc: "Powerful mandibles crush and stun defenders",
        chance: 0.2,
        duration: 1800,
      },
    ],
  },
  locust: {
    name: "Desert Locust",
    hp: 100,
    speed: 0.55,
    bounty: 7,
    armor: 0,
    flying: true,
    troopDamage: 12,
    desc: "Part of an endless swarm that devours everything in its path.",
    color: "#a3a323",
    size: 16,
    category: "swarm",
    traits: ["flying", "fast", "breakthrough"],
    breakthrough: true,
  },
  trapdoor_spider: {
    name: "Trapdoor Spider",
    hp: 280,
    speed: 0.26,
    bounty: 18,
    armor: 0.3,
    flying: false,
    troopDamage: 50,
    desc: "Ambush specialist that bursts from hidden burrows to seize prey. Wraps victims in silk.",
    color: "#78350f",
    size: 26,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "stun",
        name: "Ambush Cocoon",
        desc: "Lunges from hiding and cocoons the target",
        chance: 0.3,
        duration: 2500,
        cooldown: 7000,
      },
      {
        type: "tower_disable",
        name: "Burrow Beneath",
        desc: "Tunnels under a tower, disabling it briefly",
        chance: 0.1,
        duration: 2000,
        cooldown: 12000,
      },
    ],
  },
  // =============================================================================
  // BUG ENEMIES - Winter Region
  // =============================================================================
  ice_beetle: {
    name: "Frost Beetle",
    hp: 340,
    speed: 0.25,
    bounty: 20,
    armor: 0.4,
    flying: false,
    troopDamage: 35,
    desc: "Crystalline carapace radiates intense cold. Towers near it freeze over.",
    color: "#67e8f9",
    size: 24,
    category: "nature",
    traits: ["armored", "tower_debuffer"],
    abilities: [
      {
        type: "tower_slow",
        name: "Frost Aura",
        desc: "Extreme cold slows all nearby tower mechanisms",
        chance: 1.0,
        duration: 3000,
        intensity: 0.35,
        radius: 90,
      },
      {
        type: "slow",
        name: "Icy Bite",
        desc: "Freezing mandibles slow defenders",
        chance: 0.3,
        duration: 2000,
        intensity: 0.3,
      },
    ],
  },
  frost_tick: {
    name: "Frost Tick",
    hp: 180,
    speed: 0.38,
    bounty: 12,
    armor: 0.1,
    flying: false,
    troopDamage: 25,
    desc: "Parasitic arachnid that latches onto towers and drains their power.",
    color: "#a5f3fc",
    size: 18,
    category: "nature",
    traits: ["tower_debuffer"],
    abilities: [
      {
        type: "tower_weaken",
        name: "Power Drain",
        desc: "Latches onto towers and siphons their energy",
        chance: 1.0,
        duration: 4000,
        intensity: 0.3,
        radius: 60,
      },
    ],
  },
  snow_moth: {
    name: "Snow Moth",
    hp: 160,
    speed: 0.4,
    bounty: 11,
    armor: 0,
    flying: true,
    desc: "Ghostly moth whose frost-laden wings create whiteout conditions.",
    color: "#e0f2fe",
    size: 20,
    category: "nature",
    traits: ["flying", "tower_debuffer"],
    abilities: [
      {
        type: "tower_blind",
        name: "Whiteout Wings",
        desc: "Frost dust clouds reduce tower targeting range",
        chance: 1.0,
        duration: 3000,
        intensity: 0.35,
        radius: 70,
      },
    ],
  },
  // =============================================================================
  // BUG ENEMIES - Volcanic Region
  // =============================================================================
  fire_ant: {
    name: "Fire Ant Queen",
    hp: 450,
    speed: 0.22,
    bounty: 28,
    armor: 0.3,
    flying: false,
    troopDamage: 48,
    desc: "Matriarch of a volcanic ant colony. Endlessly spawns burning soldier ants.",
    color: "#dc2626",
    size: 30,
    category: "nature",
    traits: ["armored", "summoner"],
    summonType: "fire_imp",
    summonCount: 2,
    abilities: [
      {
        type: "burn",
        name: "Magma Spit",
        desc: "Spits burning secretions at nearby defenders",
        chance: 0.3,
        duration: 3500,
        intensity: 12,
        radius: 50,
      },
    ],
  },
  magma_beetle: {
    name: "Magma Beetle",
    hp: 380,
    speed: 0.22,
    bounty: 24,
    armor: 0.45,
    flying: false,
    troopDamage: 42,
    desc: "Living furnace encased in obsidian armor. Its molten blood burns anything that strikes it.",
    color: "#b91c1c",
    size: 26,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "burn",
        name: "Molten Shell",
        desc: "Superheated carapace burns attackers on contact",
        chance: 0.4,
        duration: 3000,
        intensity: 14,
      },
      {
        type: "tower_weaken",
        name: "Heat Warp",
        desc: "Intense heat warps tower mechanisms",
        chance: 1.0,
        duration: 2500,
        intensity: 0.2,
        radius: 60,
      },
    ],
  },
  ash_moth: {
    name: "Cinder Moth",
    hp: 170,
    speed: 0.45,
    bounty: 12,
    armor: 0.05,
    flying: true,
    desc: "Born from volcanic ash, it leaves a trail of burning embers in its wake.",
    color: "#f97316",
    size: 20,
    category: "nature",
    traits: ["flying"],
    abilities: [
      {
        type: "burn",
        name: "Ember Trail",
        desc: "Scatters burning embers that ignite defenders",
        chance: 0.35,
        duration: 2500,
        intensity: 10,
        radius: 40,
      },
    ],
  },
  // =============================================================================
  // BUG BOSS
  // =============================================================================
  brood_mother: {
    name: "Brood Mother",
    hp: 6000,
    speed: 0.12,
    bounty: 300,
    armor: 0.4,
    flying: false,
    troopDamage: 100,
    desc: "Ancient spider queen of nightmarish proportions. Spawns endless waves of spiderlings and encases defenders in unbreakable cocoons.",
    color: "#1c1917",
    size: 42,
    category: "boss",
    traits: ["armored", "boss", "summoner", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 90,
    aoeDamage: 120,
    liveCost: 8,
    summonType: "orb_weaver",
    summonCount: 3,
    abilities: [
      {
        type: "stun",
        name: "Mass Cocoon",
        desc: "Sprays silk in a wide arc, cocooning multiple defenders",
        chance: 0.2,
        duration: 3500,
        radius: 100,
        cooldown: 12000,
      },
      {
        type: "tower_disable",
        name: "Web Shroud",
        desc: "Completely encases a tower in thick webbing",
        chance: 0.15,
        duration: 4000,
        radius: 80,
        cooldown: 15000,
      },
      {
        type: "poison",
        name: "Brood Venom",
        desc: "Deadly venom weakens all nearby defenders",
        chance: 0.3,
        duration: 5000,
        intensity: 18,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // FANTASY CREATURES - Grassland Region
  // =============================================================================
  dire_bear: {
    name: "Dire Bear",
    hp: 650,
    speed: 0.2,
    bounty: 35,
    armor: 0.35,
    flying: false,
    troopDamage: 75,
    desc: "Colossal ursine predator with iron-hard hide. Its thunderous swipes send defenders flying.",
    color: "#5c3a1e",
    size: 32,
    category: "nature",
    traits: ["armored", "aoe_attack"],
    aoeRadius: 70,
    aoeDamage: 60,
    abilities: [
      {
        type: "stun",
        name: "Thunderous Swipe",
        desc: "Massive paw slam stuns all nearby defenders",
        chance: 0.25,
        duration: 2000,
        radius: 70,
        cooldown: 8000,
      },
    ],
  },
  ancient_ent: {
    name: "Ancient Ent",
    hp: 900,
    speed: 0.12,
    bounty: 45,
    armor: 0.3,
    flying: false,
    troopDamage: 60,
    desc: "A walking fortress of living wood. Roots erupt from the ground to entangle defenders, and it slowly regenerates from any wound.",
    color: "#2d5016",
    size: 36,
    category: "nature",
    traits: ["armored", "regenerating", "aoe_attack"],
    aoeRadius: 80,
    aoeDamage: 50,
    abilities: [
      {
        type: "stun",
        name: "Root Entangle",
        desc: "Roots burst from the ground, immobilizing defenders",
        chance: 0.2,
        duration: 3000,
        radius: 80,
        cooldown: 10000,
      },
      {
        type: "tower_slow",
        name: "Overgrowth",
        desc: "Vines creep into tower mechanisms",
        chance: 1.0,
        duration: 4000,
        intensity: 0.25,
        radius: 70,
      },
    ],
  },
  forest_troll: {
    name: "Forest Troll",
    hp: 480,
    speed: 0.26,
    bounty: 25,
    armor: 0.2,
    flying: false,
    troopDamage: 55,
    desc: "Regenerating brute of the deep forest. Cut it down and it rises again, angrier than before.",
    color: "#4a6741",
    size: 28,
    category: "nature",
    traits: ["armored", "regenerating"],
    abilities: [
      {
        type: "stun",
        name: "Club Smash",
        desc: "Swings a massive tree-trunk club",
        chance: 0.2,
        duration: 1500,
      },
    ],
  },
  timber_wolf: {
    name: "Timber Wolf",
    hp: 160,
    speed: 0.55,
    bounty: 10,
    armor: 0.05,
    flying: false,
    troopDamage: 28,
    desc: "Lightning-fast pack hunter. Slips past defenders before they can react.",
    color: "#6b6b6b",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "slow",
        name: "Hamstring",
        desc: "Bites at legs, slowing the target",
        chance: 0.3,
        duration: 2000,
        intensity: 0.25,
      },
    ],
  },
  giant_eagle: {
    name: "Giant Eagle",
    hp: 220,
    speed: 0.48,
    bounty: 16,
    armor: 0.05,
    flying: true,
    troopDamage: 35,
    desc: "Majestic raptor with a wingspan that blots out the sun. Swoops down to rake defenders with steel talons.",
    color: "#c8a050",
    size: 34,
    category: "nature",
    traits: ["flying", "fast"],
    abilities: [
      {
        type: "stun",
        name: "Diving Strike",
        desc: "High-speed dive stuns the target on impact",
        chance: 0.25,
        duration: 1200,
      },
    ],
  },
  // =============================================================================
  // FANTASY CREATURES - Swamp Region
  // =============================================================================
  swamp_hydra: {
    name: "Swamp Hydra",
    hp: 800,
    speed: 0.15,
    bounty: 50,
    armor: 0.25,
    flying: false,
    troopDamage: 70,
    desc: "Multi-headed serpentine horror. Each head spits venom independently, and severed heads grow back stronger.",
    color: "#2e4a2e",
    size: 34,
    category: "nature",
    traits: ["armored", "regenerating", "aoe_attack"],
    aoeRadius: 90,
    aoeDamage: 55,
    abilities: [
      {
        type: "poison",
        name: "Multi-Head Venom",
        desc: "Multiple heads spray venom simultaneously",
        chance: 0.35,
        duration: 4000,
        intensity: 14,
        radius: 70,
      },
    ],
  },
  giant_toad: {
    name: "Giant Toad",
    hp: 300,
    speed: 0.28,
    bounty: 18,
    armor: 0.15,
    flying: false,
    troopDamage: 40,
    desc: "Grotesque amphibian with a tongue that strikes like a whip. Secretes hallucinogenic toxins.",
    color: "#5a7a3a",
    size: 26,
    category: "nature",
    traits: [],
    abilities: [
      {
        type: "poison",
        name: "Toxic Secretion",
        desc: "Skin exudes paralyzing toxins",
        chance: 0.3,
        duration: 3000,
        intensity: 10,
      },
      {
        type: "stun",
        name: "Tongue Lash",
        desc: "Whip-like tongue stuns a defender at range",
        chance: 0.2,
        duration: 1500,
        cooldown: 6000,
      },
    ],
  },
  vine_serpent: {
    name: "Vine Serpent",
    hp: 250,
    speed: 0.32,
    bounty: 16,
    armor: 0.1,
    flying: false,
    troopDamage: 30,
    desc: "Living tangle of thorned vines that slithers through the swamp. Constricts towers, choking their output.",
    color: "#3a6b3a",
    size: 22,
    category: "nature",
    traits: ["tower_debuffer"],
    abilities: [
      {
        type: "tower_disable",
        name: "Constrict",
        desc: "Wraps around a tower, completely disabling it",
        chance: 0.15,
        duration: 3000,
        radius: 50,
        cooldown: 12000,
      },
      {
        type: "slow",
        name: "Thorned Grasp",
        desc: "Thorny vines slow anything they touch",
        chance: 0.3,
        duration: 2500,
        intensity: 0.3,
      },
    ],
  },
  marsh_troll: {
    name: "Marsh Troll",
    hp: 440,
    speed: 0.24,
    bounty: 24,
    armor: 0.2,
    flying: false,
    troopDamage: 50,
    desc: "Bog-dwelling regenerator caked in festering mud. Its wounds seal with toxic swamp muck.",
    color: "#4a5a3a",
    size: 28,
    category: "nature",
    traits: ["armored", "regenerating"],
    abilities: [
      {
        type: "poison",
        name: "Fetid Slam",
        desc: "Attacks leave infections that poison defenders",
        chance: 0.3,
        duration: 3500,
        intensity: 10,
      },
    ],
  },
  // =============================================================================
  // FANTASY CREATURES - Desert Region
  // =============================================================================
  phoenix: {
    name: "Phoenix",
    hp: 500,
    speed: 0.35,
    bounty: 40,
    armor: 0.1,
    flying: true,
    troopDamage: 45,
    desc: "Immortal firebird wreathed in sacred flame. Burns everything in its wake and is reborn from its own ashes.",
    color: "#ff6600",
    size: 28,
    category: "nature",
    traits: ["flying", "regenerating"],
    abilities: [
      {
        type: "burn",
        name: "Immolation Aura",
        desc: "Sacred fire burns all nearby defenders",
        chance: 1.0,
        duration: 3000,
        intensity: 15,
        radius: 60,
      },
    ],
  },
  basilisk: {
    name: "Basilisk",
    hp: 550,
    speed: 0.18,
    bounty: 35,
    armor: 0.4,
    flying: false,
    troopDamage: 55,
    desc: "Ancient stone-scaled serpent whose gaze turns flesh to stone. Impervious to most attacks.",
    color: "#6b6b3a",
    size: 30,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "stun",
        name: "Petrifying Gaze",
        desc: "Turns defenders to stone momentarily",
        chance: 0.2,
        duration: 3000,
        radius: 60,
        cooldown: 10000,
      },
      {
        type: "tower_disable",
        name: "Stone Stare",
        desc: "Petrifies a tower's mechanisms solid",
        chance: 0.1,
        duration: 2500,
        cooldown: 15000,
      },
    ],
  },
  djinn: {
    name: "Sand Djinn",
    hp: 350,
    speed: 0.34,
    bounty: 28,
    armor: 0.15,
    flying: false,
    isRanged: true,
    range: 160,
    attackSpeed: 2200,
    projectileDamage: 35,
    desc: "Ancient spirit of the desert winds. Commands sandstorms that blind and disorient defenders.",
    color: "#6a3aaa",
    size: 26,
    category: "nature",
    traits: ["ranged", "magic_resist", "tower_debuffer"],
    abilities: [
      {
        type: "tower_blind",
        name: "Sandstorm",
        desc: "Whips up blinding sands that reduce tower range",
        chance: 1.0,
        duration: 4000,
        intensity: 0.35,
        radius: 100,
      },
    ],
  },
  manticore: {
    name: "Manticore",
    hp: 420,
    speed: 0.3,
    bounty: 30,
    armor: 0.2,
    flying: true,
    isRanged: true,
    range: 150,
    attackSpeed: 1800,
    projectileDamage: 28,
    troopDamage: 45,
    desc: "Lion-bodied, bat-winged beast with a scorpion tail that launches venomous barbs at range.",
    color: "#8b4513",
    size: 28,
    category: "nature",
    traits: ["flying", "ranged", "armored"],
    abilities: [
      {
        type: "poison",
        name: "Tail Barbs",
        desc: "Launches poisoned tail spikes",
        chance: 0.35,
        duration: 3500,
        intensity: 12,
      },
    ],
  },
  // =============================================================================
  // FANTASY CREATURES - Winter Region
  // =============================================================================
  frost_troll: {
    name: "Frost Troll",
    hp: 520,
    speed: 0.22,
    bounty: 28,
    armor: 0.25,
    flying: false,
    troopDamage: 55,
    desc: "Ice-crusted regenerator that radiates bitter cold. Towers freeze solid in its presence.",
    color: "#5a8aaa",
    size: 30,
    category: "nature",
    traits: ["armored", "regenerating", "tower_debuffer"],
    abilities: [
      {
        type: "tower_slow",
        name: "Frost Aura",
        desc: "Bitter cold slows all nearby tower mechanisms",
        chance: 1.0,
        duration: 3500,
        intensity: 0.3,
        radius: 80,
      },
      {
        type: "slow",
        name: "Freezing Slam",
        desc: "Ice-covered fists freeze defenders on contact",
        chance: 0.25,
        duration: 2500,
        intensity: 0.35,
      },
    ],
  },
  dire_wolf: {
    name: "Dire Wolf",
    hp: 200,
    speed: 0.52,
    bounty: 12,
    armor: 0.15,
    flying: false,
    troopDamage: 35,
    desc: "Enormous frost-furred predator that hunts in relentless packs. Too fast and too tough to ignore.",
    color: "#4a4a5a",
    size: 22,
    category: "swarm",
    traits: ["fast", "armored"],
    abilities: [
      {
        type: "slow",
        name: "Frost Bite",
        desc: "Freezing bite slows defenders",
        chance: 0.3,
        duration: 2000,
        intensity: 0.25,
      },
    ],
  },
  wendigo: {
    name: "Wendigo",
    hp: 380,
    speed: 0.4,
    bounty: 25,
    armor: 0.15,
    flying: false,
    troopDamage: 60,
    desc: "Gaunt horror of the frozen wastes. Its shriek paralyzes defenders with primal terror.",
    color: "#3a3a4a",
    size: 26,
    category: "nature",
    traits: ["fast", "tower_debuffer"],
    abilities: [
      {
        type: "tower_disable",
        name: "Terror Shriek",
        desc: "Bloodcurdling scream disables towers with fear",
        chance: 0.15,
        duration: 2500,
        radius: 70,
        cooldown: 12000,
      },
      {
        type: "stun",
        name: "Rending Claws",
        desc: "Savage claws stun defenders",
        chance: 0.2,
        duration: 1500,
      },
    ],
  },
  mammoth: {
    name: "War Mammoth",
    hp: 4000,
    speed: 0.11,
    bounty: 150,
    armor: 0.55,
    flying: false,
    troopDamage: 150,
    isRanged: true,
    range: 200,
    attackSpeed: 2800,
    projectileDamage: 65,
    desc: "Colossal armored beast carrying a war howdah of archers. Its iron-tipped tusks and seismic charge flatten all resistance.",
    color: "#8b7355",
    size: 52,
    category: "nature",
    traits: ["armored", "aoe_attack", "ranged"],
    aoeRadius: 130,
    aoeDamage: 120,
    liveCost: 6,
    abilities: [
      {
        type: "stun",
        name: "Seismic Stomp",
        desc: "Thunderous footsteps stun all nearby defenders",
        chance: 0.2,
        duration: 2500,
        radius: 120,
        cooldown: 8000,
      },
      {
        type: "tower_weaken",
        name: "Tremor",
        desc: "Ground shaking disrupts tower accuracy",
        chance: 1.0,
        duration: 3000,
        intensity: 0.25,
        radius: 110,
      },
    ],
  },
  // =============================================================================
  // FANTASY CREATURES - Volcanic Region
  // =============================================================================
  lava_golem: {
    name: "Lava Golem",
    hp: 700,
    speed: 0.16,
    bounty: 40,
    armor: 0.5,
    flying: false,
    troopDamage: 65,
    desc: "Living mountain of molten rock and obsidian. Nearly indestructible and burns everything it touches.",
    color: "#8b2500",
    size: 34,
    category: "nature",
    traits: ["armored"],
    abilities: [
      {
        type: "burn",
        name: "Molten Aura",
        desc: "Radiates intense heat that burns all nearby",
        chance: 1.0,
        duration: 3000,
        intensity: 16,
        radius: 70,
      },
      {
        type: "tower_weaken",
        name: "Heat Distortion",
        desc: "Extreme heat warps tower mechanisms",
        chance: 1.0,
        duration: 3000,
        intensity: 0.25,
        radius: 80,
      },
    ],
  },
  volcanic_drake: {
    name: "Volcanic Drake",
    hp: 450,
    speed: 0.32,
    bounty: 32,
    armor: 0.2,
    flying: true,
    troopDamage: 50,
    desc: "Fire-breathing drake born from volcanic vents. Rains molten fire from above.",
    color: "#cc3300",
    size: 28,
    category: "nature",
    traits: ["flying", "armored"],
    abilities: [
      {
        type: "burn",
        name: "Fire Breath",
        desc: "Exhales a cone of dragonfire",
        chance: 0.35,
        duration: 3500,
        intensity: 14,
        radius: 60,
      },
    ],
  },
  salamander: {
    name: "Fire Salamander",
    hp: 280,
    speed: 0.42,
    bounty: 18,
    armor: 0.15,
    flying: false,
    troopDamage: 35,
    desc: "Swift elemental lizard that regenerates in flame. Leaves a trail of burning footprints.",
    color: "#ff4500",
    size: 22,
    category: "nature",
    traits: ["fast", "regenerating"],
    abilities: [
      {
        type: "burn",
        name: "Flame Trail",
        desc: "Leaves burning footprints that scorch defenders",
        chance: 0.4,
        duration: 2500,
        intensity: 10,
      },
    ],
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Skeletons
  // =============================================================================
  skeleton_footman: {
    name: "Prospect Street Bones",
    hp: 180,
    speed: 0.48,
    bounty: 10,
    armor: 0,
    flying: false,
    troopDamage: 14,
    desc: "Rattling remnants of a forgotten eating club member. Fast but fragile.",
    color: "#d4c5a0",
    size: 20,
    category: "swarm",
    traits: ["fast"],
  },
  skeleton_knight: {
    name: "Old Guard Skeleton",
    hp: 550,
    speed: 0.28,
    bounty: 40,
    armor: 0.35,
    flying: false,
    troopDamage: 52,
    desc: "Ancient warrior bound by tradition. Rusted armor still holds strong.",
    color: "#8b8068",
    size: 26,
    category: "campus",
    traits: ["armored"],
    abilities: [
      {
        type: "stun",
        name: "Shield Bash",
        desc: "Bashes defenders with a corroded shield",
        chance: 0.2,
        duration: 1200,
      },
    ],
  },
  skeleton_archer: {
    name: "Blair Arch Bowman",
    hp: 260,
    speed: 0.32,
    bounty: 28,
    armor: 0.05,
    flying: false,
    isRanged: true,
    range: 200,
    attackSpeed: 2000,
    projectileDamage: 38,
    desc: "Skeletal sharpshooter perched in the arches. Never misses.",
    color: "#c4b590",
    size: 22,
    category: "ranged",
    traits: ["ranged"],
    abilities: [
      {
        type: "poison",
        name: "Bone Splinter",
        desc: "Arrows fragment into poisoned bone shards",
        chance: 0.25,
        duration: 3000,
        intensity: 8,
      },
    ],
  },
  skeleton_king: {
    name: "Nassau Hall Overlord",
    hp: 5500,
    speed: 0.14,
    bounty: 250,
    armor: 0.45,
    flying: false,
    troopDamage: 130,
    desc: "The crowned sovereign of Nassau's catacombs. Commands legions of bone.",
    color: "#daa520",
    size: 38,
    category: "boss",
    traits: ["armored", "boss", "summoner", "aoe_attack"],
    isBoss: true,
    aoeRadius: 100,
    aoeDamage: 140,
    liveCost: 6,
    summonType: "skeleton_footman",
    summonCount: 3,
    abilities: [
      {
        type: "tower_disable",
        name: "Royal Decree",
        desc: "Sovereign authority shuts down towers completely",
        chance: 0.15,
        duration: 3500,
        radius: 120,
        cooldown: 10000,
      },
      {
        type: "stun",
        name: "Bone Throne Slam",
        desc: "Slams his scepter, stunning all nearby defenders",
        chance: 0.25,
        duration: 2000,
        radius: 100,
      },
    ],
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Zombies
  // =============================================================================
  zombie_shambler: {
    name: "Monday 8AM Shambler",
    hp: 250,
    speed: 0.2,
    bounty: 8,
    armor: 0,
    flying: false,
    troopDamage: 18,
    desc: "Groaning corpse with the energy of a Monday morning student. Slow but relentless.",
    color: "#5a7247",
    size: 21,
    category: "swarm",
    traits: [],
    abilities: [
      {
        type: "slow",
        name: "Contagious Lethargy",
        desc: "Infectious laziness slows defenders",
        chance: 0.2,
        duration: 2000,
        intensity: 0.15,
      },
    ],
  },
  zombie_brute: {
    name: "Midterm Mauler",
    hp: 1200,
    speed: 0.15,
    bounty: 70,
    armor: 0.4,
    flying: false,
    troopDamage: 90,
    desc: "Bloated undead horror wrapped in rusted chains. Absorbs punishment endlessly.",
    color: "#4a5d3a",
    size: 32,
    category: "campus",
    traits: ["armored", "aoe_attack"],
    aoeRadius: 70,
    aoeDamage: 80,
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Crushing Grip",
        desc: "Grabs and stuns defenders with immense force",
        chance: 0.2,
        duration: 1500,
      },
      {
        type: "poison",
        name: "Rotting Aura",
        desc: "Decaying flesh poisons nearby defenders",
        chance: 0.3,
        duration: 4000,
        intensity: 10,
        radius: 70,
      },
    ],
  },
  zombie_spitter: {
    name: "Dining Hall Revenant",
    hp: 340,
    speed: 0.22,
    bounty: 30,
    armor: 0.1,
    flying: false,
    isRanged: true,
    range: 180,
    attackSpeed: 2400,
    projectileDamage: 55,
    desc: "Reanimated cafeteria horror. Spews toxic bile at defenders.",
    color: "#7cb342",
    size: 24,
    category: "ranged",
    traits: ["ranged"],
    abilities: [
      {
        type: "poison",
        name: "Acid Bile",
        desc: "Corrosive vomit poisons and weakens targets",
        chance: 0.35,
        duration: 3500,
        intensity: 12,
      },
    ],
  },
  ghoul: {
    name: "All-Nighter Ghoul",
    hp: 280,
    speed: 0.55,
    bounty: 18,
    armor: 0,
    flying: false,
    troopDamage: 22,
    desc: "Feral undead driven mad by sleep deprivation. Sprints through defenses.",
    color: "#6b5b73",
    size: 20,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "slow",
        name: "Paralyzing Shriek",
        desc: "Bloodcurdling scream briefly slows nearby defenders",
        chance: 0.2,
        duration: 1500,
        intensity: 0.25,
        radius: 50,
      },
    ],
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Dark Knights
  // =============================================================================
  dark_knight: {
    name: "Cannon Green Champion",
    hp: 1500,
    speed: 0.22,
    bounty: 100,
    armor: 0.5,
    flying: false,
    troopDamage: 105,
    desc: "Fell warrior in obsidian plate. Each step cracks the earth.",
    color: "#2d2d3d",
    size: 30,
    category: "campus",
    traits: ["armored"],
    liveCost: 2,
    abilities: [
      {
        type: "stun",
        name: "Dark Cleave",
        desc: "Devastating sword strike stuns defenders",
        chance: 0.25,
        duration: 1500,
      },
      {
        type: "tower_weaken",
        name: "Dread Presence",
        desc: "Aura of dread weakens nearby towers",
        chance: 1.0,
        duration: 3000,
        intensity: 0.2,
        radius: 80,
      },
    ],
  },
  death_knight: {
    name: "FitzRandolph Dread Lord",
    hp: 6000,
    speed: 0.16,
    bounty: 300,
    armor: 0.55,
    flying: false,
    troopDamage: 150,
    desc: "Undead champion of the gate. His cursed blade devours souls.",
    color: "#1a1a2e",
    size: 36,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 100,
    aoeDamage: 160,
    liveCost: 8,
    abilities: [
      {
        type: "tower_disable",
        name: "Soul Reap",
        desc: "Drains tower energy completely",
        chance: 0.15,
        duration: 4000,
        radius: 120,
        cooldown: 10000,
      },
      {
        type: "burn",
        name: "Unholy Flame",
        desc: "Cursed fire burns defenders from within",
        chance: 0.3,
        duration: 4000,
        intensity: 20,
        radius: 90,
      },
      {
        type: "stun",
        name: "Dread Slam",
        desc: "Massive shockwave stuns all nearby",
        chance: 0.2,
        duration: 2200,
        radius: 110,
      },
    ],
  },
  fallen_paladin: {
    name: "Fallen Ivy Champion",
    hp: 2000,
    speed: 0.2,
    bounty: 130,
    armor: 0.4,
    flying: false,
    troopDamage: 110,
    desc: "Once a defender of the league, now corrupted by dark ambition.",
    color: "#4a3f6b",
    size: 32,
    category: "campus",
    traits: ["armored", "magic_resist"],
    liveCost: 3,
    abilities: [
      {
        type: "burn",
        name: "Corrupted Smite",
        desc: "Dark holy fire sears defenders",
        chance: 0.3,
        duration: 3500,
        intensity: 18,
      },
      {
        type: "tower_weaken",
        name: "Aura of Corruption",
        desc: "Corrupting presence reduces tower damage",
        chance: 1.0,
        duration: 4000,
        intensity: 0.3,
        radius: 100,
      },
    ],
  },
  black_guard: {
    name: "Holder Hall Sentinel",
    hp: 900,
    speed: 0.25,
    bounty: 60,
    armor: 0.45,
    flying: false,
    troopDamage: 72,
    desc: "Elite guardian clad in midnight steel. Nearly impenetrable.",
    color: "#1c1c2e",
    size: 28,
    category: "campus",
    traits: ["armored"],
    abilities: [
      {
        type: "stun",
        name: "Shield Wall",
        desc: "Blocks and stuns attackers with massive shield",
        chance: 0.2,
        duration: 1300,
      },
    ],
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Dark Casters
  // =============================================================================
  lich: {
    name: "Emeritus Lich",
    hp: 3000,
    speed: 0.12,
    bounty: 200,
    armor: 0.3,
    flying: false,
    isRanged: true,
    range: 250,
    attackSpeed: 3000,
    projectileDamage: 120,
    troopDamage: 100,
    desc: "An emeritus professor who refused to retire. Now an undead archmage.",
    color: "#4fc3f7",
    size: 34,
    category: "boss",
    traits: ["ranged", "boss", "summoner", "magic_resist", "tower_debuffer"],
    isBoss: true,
    liveCost: 5,
    summonType: "bone_mage",
    summonCount: 2,
    abilities: [
      {
        type: "tower_disable",
        name: "Arcane Lockdown",
        desc: "Seals towers in arcane ice",
        chance: 0.15,
        duration: 3500,
        radius: 130,
        cooldown: 12000,
      },
      {
        type: "slow",
        name: "Frost Nova",
        desc: "Freezing blast slows all nearby",
        chance: 0.3,
        duration: 3000,
        intensity: 0.4,
        radius: 100,
      },
    ],
  },
  wraith: {
    name: "Chapel Wraith",
    hp: 450,
    speed: 0.5,
    bounty: 55,
    armor: 0.5,
    flying: true,
    troopDamage: 45,
    desc: "Ethereal horror that drifts through the chapel at midnight.",
    color: "#b39ddb",
    size: 24,
    category: "flying",
    traits: ["flying", "magic_resist", "armored"],
    targetsTroops: true,
    troopAttackSpeed: 1800,
    liveCost: 2,
    abilities: [
      {
        type: "tower_slow",
        name: "Spectral Chill",
        desc: "Ghostly presence slows tower mechanisms",
        chance: 1.0,
        duration: 2500,
        intensity: 0.25,
        radius: 80,
      },
    ],
  },
  bone_mage: {
    name: "McCosh Bone Scholar",
    hp: 380,
    speed: 0.24,
    bounty: 45,
    armor: 0.1,
    flying: false,
    isRanged: true,
    range: 210,
    attackSpeed: 2500,
    projectileDamage: 65,
    desc: "Skeletal scholar who weaponized forbidden osteomancy.",
    color: "#ce93d8",
    size: 24,
    category: "ranged",
    traits: ["ranged", "magic_resist"],
    abilities: [
      {
        type: "tower_weaken",
        name: "Bone Curse",
        desc: "Curses towers, reducing their effectiveness",
        chance: 0.25,
        duration: 3000,
        intensity: 0.2,
        radius: 90,
      },
    ],
  },
  dark_priest: {
    name: "Cloister Heretic",
    hp: 600,
    speed: 0.2,
    bounty: 65,
    armor: 0.15,
    flying: false,
    troopDamage: 55,
    desc: "Excommunicated cleric channeling forbidden rites in the cloisters.",
    color: "#5c1a1a",
    size: 26,
    category: "campus",
    traits: ["tower_debuffer"],
    abilities: [
      {
        type: "tower_slow",
        name: "Dark Prayer",
        desc: "Unholy chanting disrupts tower mechanisms",
        chance: 1.0,
        duration: 4000,
        intensity: 0.3,
        radius: 100,
      },
      {
        type: "poison",
        name: "Blight",
        desc: "Corrupting miasma poisons defenders",
        chance: 0.3,
        duration: 4500,
        intensity: 12,
        radius: 80,
      },
    ],
  },
  // =============================================================================
  // DARK FANTASY ENEMIES - Monstrous
  // =============================================================================
  revenant: {
    name: "Whig-Clio Revenant",
    hp: 1100,
    speed: 0.35,
    bounty: 80,
    armor: 0.25,
    flying: false,
    troopDamage: 85,
    desc: "Vengeful spirit of a debater who lost their final argument. Relentless.",
    color: "#c62828",
    size: 28,
    category: "campus",
    traits: ["fast"],
    liveCost: 2,
    abilities: [
      {
        type: "burn",
        name: "Vengeance Flame",
        desc: "Burning rage sears nearby defenders",
        chance: 0.3,
        duration: 3000,
        intensity: 15,
      },
      {
        type: "stun",
        name: "Wrathful Strike",
        desc: "Furious blow stuns defenders",
        chance: 0.2,
        duration: 1200,
      },
    ],
  },
  abomination: {
    name: "Lab Section Abomination",
    hp: 8000,
    speed: 0.1,
    bounty: 350,
    armor: 0.35,
    flying: false,
    troopDamage: 170,
    desc: "Grotesque stitched monstrosity from a biology experiment gone horribly wrong.",
    color: "#4e342e",
    size: 42,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "regenerating"],
    isBoss: true,
    aoeRadius: 110,
    aoeDamage: 180,
    liveCost: 8,
    abilities: [
      {
        type: "poison",
        name: "Toxic Spray",
        desc: "Spews horrific chemicals that poison all nearby",
        chance: 0.35,
        duration: 5000,
        intensity: 18,
        radius: 100,
      },
      {
        type: "stun",
        name: "Ground Pound",
        desc: "Massive slam stuns all nearby defenders",
        chance: 0.25,
        duration: 2000,
        radius: 100,
      },
    ],
  },
  hellhound: {
    name: "Tiger Hollow Hellhound",
    hp: 350,
    speed: 0.65,
    bounty: 25,
    armor: 0,
    flying: false,
    troopDamage: 30,
    desc: "Demonic beast that blazes through defenses like wildfire.",
    color: "#ff6f00",
    size: 22,
    category: "swarm",
    traits: ["fast", "breakthrough"],
    breakthrough: true,
    abilities: [
      {
        type: "burn",
        name: "Hellfire Bite",
        desc: "Flaming jaws leave burning wounds",
        chance: 0.3,
        duration: 2500,
        intensity: 10,
      },
    ],
  },
  doom_herald: {
    name: "Reunions Doom Herald",
    hp: 7000,
    speed: 0.18,
    bounty: 400,
    armor: 0.4,
    flying: true,
    isRanged: true,
    range: 230,
    attackSpeed: 2500,
    projectileDamage: 130,
    troopDamage: 140,
    desc: "Dark seraphim descending upon Reunions. The party ends now.",
    color: "#311b92",
    size: 40,
    category: "boss",
    traits: ["flying", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 110,
    aoeDamage: 200,
    targetsTroops: true,
    troopAttackSpeed: 2500,
    liveCost: 10,
    abilities: [
      {
        type: "tower_disable",
        name: "Eclipse",
        desc: "Blankets the field in darkness, disabling towers",
        chance: 0.15,
        duration: 4500,
        radius: 150,
        cooldown: 14000,
      },
      {
        type: "burn",
        name: "Dark Fire",
        desc: "Unholy flames consume all in their path",
        chance: 0.3,
        duration: 4500,
        intensity: 22,
        radius: 100,
      },
      {
        type: "stun",
        name: "Doom Shockwave",
        desc: "Devastating blast stuns all nearby",
        chance: 0.2,
        duration: 2500,
        radius: 120,
      },
    ],
  },
  // =============================================================================
  // REGIONAL GIANT BOSSES - End-of-region mega bosses
  // =============================================================================
  titan_of_nassau: {
    name: "The Nassau Colossus",
    hp: 18000,
    speed: 0.08,
    bounty: 600,
    armor: 0.45,
    flying: false,
    troopDamage: 200,
    desc: "A colossal stone tiger awakened from Nassau Hall's foundation. Ancient ivy pulses with arcane energy through its joints, and its eyes blaze with Princeton orange fire. The ground trembles with every step.",
    color: "#e65100",
    size: 52,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 130,
    aoeDamage: 220,
    liveCost: 15,
    abilities: [
      {
        type: "tower_disable",
        name: "Petrifying Roar",
        desc: "Earth-shaking roar turns towers to stone temporarily",
        chance: 0.15,
        duration: 5000,
        radius: 160,
        cooldown: 12000,
      },
      {
        type: "stun",
        name: "Seismic Stomp",
        desc: "Massive paws shake the earth, stunning all defenders",
        chance: 0.25,
        duration: 2800,
        radius: 140,
      },
      {
        type: "burn",
        name: "Tiger's Wrath",
        desc: "Princeton flame pours from its maw, burning everything",
        chance: 0.3,
        duration: 5000,
        intensity: 30,
        radius: 120,
      },
    ],
  },
  swamp_leviathan: {
    name: "The Thesis Hydra",
    hp: 16000,
    speed: 0.1,
    bounty: 550,
    armor: 0.35,
    flying: false,
    troopDamage: 180,
    desc: "A writhing multi-headed serpentine horror risen from the academic swamps. Each head represents an unfinishable chapter — cut one down and another argument emerges. Toxic scholarly bile drips from every maw.",
    color: "#1b5e20",
    size: 50,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "regenerating", "summoner"],
    isBoss: true,
    aoeRadius: 120,
    aoeDamage: 200,
    liveCost: 12,
    summonType: "bog_creature",
    summonCount: 2,
    abilities: [
      {
        type: "poison",
        name: "Thesis Bile",
        desc: "Corrosive academic dread poisons all nearby",
        chance: 0.35,
        duration: 6000,
        intensity: 25,
        radius: 120,
      },
      {
        type: "stun",
        name: "Tail Crush",
        desc: "Massive tail sweeps stun all nearby defenders",
        chance: 0.25,
        duration: 2200,
        radius: 130,
      },
      {
        type: "tower_weaken",
        name: "Miasma of Doubt",
        desc: "Fog of academic uncertainty weakens towers",
        chance: 1.0,
        duration: 5000,
        intensity: 0.35,
        radius: 140,
      },
    ],
  },
  sphinx_guardian: {
    name: "The Midterm Sphinx",
    hp: 20000,
    speed: 0.07,
    bounty: 700,
    armor: 0.5,
    flying: false,
    troopDamage: 220,
    desc: "An ancient colossal sphinx carved from sandstone and gold. It poses unanswerable riddles that disable the minds of defenders. Its gaze alone can shatter towers. The ultimate exam you can never be ready for.",
    color: "#f9a825",
    size: 54,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer", "magic_resist"],
    isBoss: true,
    aoeRadius: 140,
    aoeDamage: 240,
    liveCost: 15,
    abilities: [
      {
        type: "tower_disable",
        name: "Unsolvable Riddle",
        desc: "Poses an impossible question that freezes tower logic",
        chance: 0.15,
        duration: 5500,
        radius: 170,
        cooldown: 14000,
      },
      {
        type: "stun",
        name: "Judgmental Gaze",
        desc: "Piercing stare paralyzes all who meet it",
        chance: 0.25,
        duration: 3000,
        radius: 150,
      },
      {
        type: "tower_weaken",
        name: "Curse of Ignorance",
        desc: "Ancient curse makes towers forget their training",
        chance: 1.0,
        duration: 5500,
        intensity: 0.4,
        radius: 160,
      },
      {
        type: "slow",
        name: "Time Dilation",
        desc: "Warps time around it, slowing all nearby",
        chance: 1.0,
        duration: 4000,
        intensity: 0.5,
        radius: 130,
      },
    ],
  },
  frost_colossus: {
    name: "The January Titan",
    hp: 17000,
    speed: 0.09,
    bounty: 650,
    armor: 0.55,
    flying: false,
    troopDamage: 210,
    desc: "An enormous crystalline ice giant born from the brutal January cold. Blizzards rage within its translucent body and every surface it passes freezes solid. The embodiment of winter's cruelty.",
    color: "#4dd0e1",
    size: 52,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer"],
    isBoss: true,
    aoeRadius: 130,
    aoeDamage: 210,
    liveCost: 12,
    abilities: [
      {
        type: "slow",
        name: "Absolute Zero",
        desc: "Freezing aura slows everything to a crawl",
        chance: 1.0,
        duration: 5000,
        intensity: 0.55,
        radius: 150,
      },
      {
        type: "tower_disable",
        name: "Flash Freeze",
        desc: "Encases towers in solid ice",
        chance: 0.15,
        duration: 4500,
        radius: 140,
        cooldown: 11000,
      },
      {
        type: "stun",
        name: "Glacier Slam",
        desc: "Brings fists down like avalanches, stunning all",
        chance: 0.25,
        duration: 2500,
        radius: 130,
      },
      {
        type: "tower_slow",
        name: "Permafrost",
        desc: "Permanent chill slows tower mechanisms drastically",
        chance: 1.0,
        duration: 6000,
        intensity: 0.45,
        radius: 160,
      },
    ],
  },
  inferno_wyrm: {
    name: "The Burnout Wyrm",
    hp: 22000,
    speed: 0.06,
    bounty: 800,
    armor: 0.4,
    flying: false,
    troopDamage: 250,
    desc: "A titanic lava serpent that erupts from the volcanic depths. Molten scales drip liquid fire, its body stretches across the battlefield, and the air itself ignites in its wake. The ultimate embodiment of academic burnout.",
    color: "#d50000",
    size: 56,
    category: "boss",
    traits: ["armored", "boss", "aoe_attack", "tower_debuffer", "regenerating"],
    isBoss: true,
    aoeRadius: 150,
    aoeDamage: 280,
    liveCost: 20,
    abilities: [
      {
        type: "burn",
        name: "Magma Eruption",
        desc: "Erupts molten fire that scorches everything in sight",
        chance: 0.35,
        duration: 6000,
        intensity: 35,
        radius: 150,
      },
      {
        type: "tower_disable",
        name: "Volcanic Overload",
        desc: "Extreme heat causes tower meltdown",
        chance: 0.15,
        duration: 5000,
        radius: 160,
        cooldown: 13000,
      },
      {
        type: "stun",
        name: "Tectonic Shatter",
        desc: "Slams its body into the earth, stunning all defenders",
        chance: 0.25,
        duration: 3000,
        radius: 140,
      },
      {
        type: "tower_weaken",
        name: "Heat Distortion",
        desc: "Intense heat warps reality, reducing tower effectiveness",
        chance: 1.0,
        duration: 5500,
        intensity: 0.4,
        radius: 170,
      },
    ],
  },
};

// =============================================================================
// ENEMY TRAIT DISPLAY METADATA
// =============================================================================

export interface EnemyTraitMeta {
  label: string;
  color: string;
  desc: string;
  pillColor: string;
}

export const ENEMY_TRAIT_META: Record<EnemyTrait, EnemyTraitMeta> = {
  flying: { label: "Flying", color: "text-cyan-400", desc: "Ignores ground obstacles, only hit by certain towers", pillColor: "bg-cyan-900/60 text-cyan-300 border-cyan-700/40" },
  ranged: { label: "Ranged", color: "text-green-400", desc: "Attacks from a distance", pillColor: "bg-green-900/60 text-green-300 border-green-700/40" },
  armored: { label: "Armored", color: "text-amber-400", desc: "Reduces incoming damage", pillColor: "bg-blue-900/60 text-blue-300 border-blue-700/40" },
  fast: { label: "Fast", color: "text-yellow-400", desc: "Moves faster than normal enemies", pillColor: "bg-yellow-900/60 text-yellow-300 border-yellow-700/40" },
  boss: { label: "Boss", color: "text-red-400", desc: "Powerful elite enemy with high HP", pillColor: "bg-red-900/60 text-red-300 border-red-700/40" },
  summoner: { label: "Summoner", color: "text-purple-400", desc: "Can summon additional enemies", pillColor: "bg-purple-900/60 text-purple-300 border-purple-700/40" },
  regenerating: { label: "Regen", color: "text-green-400", desc: "Slowly recovers health over time", pillColor: "bg-emerald-900/60 text-emerald-300 border-emerald-700/40" },
  aoe_attack: { label: "AoE", color: "text-orange-400", desc: "Attacks hit multiple targets", pillColor: "bg-orange-900/60 text-orange-300 border-orange-700/40" },
  magic_resist: { label: "Magic Resist", color: "text-blue-400", desc: "Reduced damage from magic attacks", pillColor: "bg-indigo-900/60 text-indigo-300 border-indigo-700/40" },
  tower_debuffer: { label: "Debuffer", color: "text-rose-400", desc: "Can weaken or disable towers", pillColor: "bg-rose-900/60 text-rose-300 border-rose-700/40" },
  breakthrough: { label: "Breakthrough", color: "text-sky-400", desc: "Bypasses barracks troops without stopping", pillColor: "bg-amber-900/60 text-amber-300 border-amber-700/40" },
};

// =============================================================================
// ENEMY ABILITY TYPE DISPLAY METADATA
// =============================================================================

export interface EnemyAbilityMeta {
  color: string;
  bgColor: string;
}

export const ENEMY_ABILITY_META: Record<EnemyAbilityType | "default", EnemyAbilityMeta> = {
  burn: { color: "text-orange-400", bgColor: "bg-orange-950/60 border-orange-800/50" },
  slow: { color: "text-cyan-400", bgColor: "bg-cyan-950/60 border-cyan-800/50" },
  poison: { color: "text-green-400", bgColor: "bg-green-950/60 border-green-800/50" },
  stun: { color: "text-yellow-400", bgColor: "bg-yellow-950/60 border-yellow-800/50" },
  tower_slow: { color: "text-blue-400", bgColor: "bg-blue-950/60 border-blue-800/50" },
  tower_weaken: { color: "text-red-400", bgColor: "bg-red-950/60 border-red-800/50" },
  tower_blind: { color: "text-purple-400", bgColor: "bg-purple-950/60 border-purple-800/50" },
  tower_disable: { color: "text-rose-400", bgColor: "bg-rose-950/60 border-rose-800/50" },
  default: { color: "text-gray-400", bgColor: "bg-gray-950/60 border-gray-800/50" },
};

// =============================================================================
// ENEMY CATEGORY DISPLAY METADATA
// =============================================================================

export interface EnemyCategoryMeta {
  name: string;
  desc: string;
  color: string;
  bgColor: string;
}

export const ENEMY_CATEGORY_META: Record<EnemyCategory, EnemyCategoryMeta> = {
  academic: { name: "Academic", desc: "Academic progression and milestones", color: "text-purple-400", bgColor: "bg-purple-950/50 border-purple-800/40" },
  campus: { name: "Campus Life", desc: "Campus events and activities", color: "text-amber-400", bgColor: "bg-amber-950/50 border-amber-800/40" },
  ranged: { name: "Ranged", desc: "Attack from a distance", color: "text-green-400", bgColor: "bg-green-950/50 border-green-800/40" },
  flying: { name: "Flying", desc: "Aerial threats that bypass ground obstacles", color: "text-cyan-400", bgColor: "bg-cyan-950/50 border-cyan-800/40" },
  boss: { name: "Bosses", desc: "Major threats with devastating power", color: "text-red-400", bgColor: "bg-red-950/50 border-red-800/40" },
  nature: { name: "Nature", desc: "Environmental and biome creatures", color: "text-emerald-400", bgColor: "bg-emerald-950/50 border-emerald-800/40" },
  swarm: { name: "Swarm", desc: "Fast and numerous, strength in numbers", color: "text-yellow-400", bgColor: "bg-yellow-950/50 border-yellow-800/40" },
};

export const ENEMY_CATEGORY_ORDER: EnemyCategory[] = ["academic", "campus", "ranged", "flying", "boss", "nature", "swarm"];

export const ENEMY_CATEGORY_ACCENTS: Record<EnemyCategory, string> = {
  academic: "#c084fc",
  campus: "#f59e0b",
  ranged: "#4ade80",
  flying: "#22d3ee",
  boss: "#f87171",
  nature: "#34d399",
  swarm: "#facc15",
};

export function groupEnemiesByCategory(enemyTypes: EnemyType[]): Record<EnemyCategory, EnemyType[]> {
  const grouped: Record<EnemyCategory, EnemyType[]> = {
    academic: [], campus: [], ranged: [], flying: [], boss: [], nature: [], swarm: [],
  };
  for (const type of enemyTypes) {
    const enemy = ENEMY_DATA[type];
    const category = enemy.category || "campus";
    grouped[category].push(type);
  }
  return grouped;
}
