import type { TroopData, TroopType } from "../types";

// Troop data - includes "elite" for Level 3 station
export const TROOP_DATA: Record<TroopType, TroopData> = {
  footsoldier: {
    name: "Foot Soldier",
    hp: 700,
    damage: 20,
    attackSpeed: 1100,
    desc: "Scrappy garrison recruit wielding a gladius and scutum shield. Determined to hold the line despite worn equipment.",
    color: "#6b8e23",
  },
  armored: {
    name: "Armored Soldier",
    hp: 1100,
    damage: 25,
    attackSpeed: 1000,
    desc: "Plate-clad sentinel carrying a flanged mace and heater shield. Built to absorb punishment that would fell lesser soldiers.",
    color: "#708090",
  },
  elite: {
    name: "Elite Guard",
    hp: 1400,
    damage: 35,
    attackSpeed: 900,
    desc: "Veteran halberdier in gilded armor bearing the Princeton crest. Strikes with disciplined reach and precision.",
    color: "#c0c0c0",
  },
  knight: {
    name: "Knight",
    hp: 1800,
    damage: 52,
    attackSpeed: 850,
    desc: "Champion in full plate, each bearing uniquely forged armor and weaponry. The garrison's finest and most fearsome.",
    color: "#c0c0c0",
  },
  reinforcement: {
    name: "Reinforcement",
    hp: 1000,
    damage: 30,
    attackSpeed: 1000,
    desc: "Arcane warrior conjured by battlefield sorcery, each arriving in uniquely enchanted plate and helm. Grows stronger with spell upgrades.",
    color: "#a78bfa",
  },
  centaur: {
    name: "Centaur",
    hp: 1200,
    damage: 45,
    attackSpeed: 700,
    desc: "Golden war-archer mounted on a powerful steed. Looses precise volleys that can strike even airborne targets.",
    color: "#8b4513",
    isMounted: true,
    isRanged: true,
    range: 280,
    canTargetFlying: true,
  },
  cavalry: {
    name: "Cavalry",
    hp: 1800,
    damage: 55,
    attackSpeed: 1100,
    desc: "Thundering lancer atop a royal war steed in burnished armor. Devastating on the charge and nearly impossible to dislodge.",
    color: "#daa520",
    isMounted: true,
  },
  thesis: {
    name: "Hexthesis",
    hp: 1400,
    damage: 55,
    attackSpeed: 750,
    desc: "Reanimated scholar bound by hex magic and forged from elite souls. Channels forbidden knowledge into devastating strikes.",
    color: "#a855f7",
  },
  rowing: {
    name: "Hexrower",
    hp: 1700,
    damage: 45,
    attackSpeed: 1000,
    desc: "Hulking specter dragged back by a violet curse. Swings with relentless, bone-crushing force that few can withstand.",
    color: "#8b5cf6",
  },
  hexling: {
    name: "Hexling",
    hp: 1050,
    damage: 34,
    attackSpeed: 880,
    desc: "Flickering spirit of malice that hurls occult bolts from afar. Can strike both grounded and airborne foes.",
    color: "#c026d3",
    isRanged: true,
    range: 240,
    canTargetFlying: true,
  },
  hexseer: {
    name: "Hexseer",
    hp: 1500,
    damage: 58,
    attackSpeed: 720,
    desc: "Ascendant hex caster woven from powerful souls. Its eldritch volleys reach further and hit harder than any lesser spirit.",
    color: "#f472b6",
    isRanged: true,
    range: 290,
    canTargetFlying: true,
  },
  turret: {
    name: "Defense Turret",
    hp: 800,
    damage: 35,
    attackSpeed: 800,
    desc: "Mechanical siege emplacement that rains bolts on nearby threats. Immobile but relentless once deployed.",
    color: "#f59e0b",
    isRanged: true,
    range: 140,
    isStationary: true,
  },
};
