import type { TroopData, TroopType } from "../types";

// Troop data - includes "elite" for Level 3 station
export const TROOP_DATA: Record<TroopType, TroopData> = {
  armored: {
    attackSpeed: 1000,
    color: "#708090",
    damage: 25,
    desc: "Plate-clad sentinel carrying a flanged mace and heater shield. Built to absorb punishment that would fell lesser soldiers.",
    hp: 1100,
    name: "Armored Soldier",
  },
  cavalry: {
    attackSpeed: 1100,
    color: "#daa520",
    damage: 55,
    desc: "Thundering lancer atop a royal war steed in burnished armor. Devastating on the charge and nearly impossible to dislodge.",
    hp: 1800,
    isMounted: true,
    name: "Cavalry",
  },
  centaur: {
    attackSpeed: 700,
    canTargetFlying: true,
    color: "#8b4513",
    damage: 45,
    desc: "Golden war-archer mounted on a powerful steed. Looses precise volleys that can strike even airborne targets.",
    hp: 1200,
    isMounted: true,
    isRanged: true,
    name: "Centaur",
    range: 280,
  },
  elite: {
    attackSpeed: 900,
    color: "#c0c0c0",
    damage: 35,
    desc: "Veteran halberdier in gilded armor bearing the Princeton crest. Strikes with disciplined reach and precision.",
    hp: 1400,
    name: "Elite Guard",
  },
  footsoldier: {
    attackSpeed: 1100,
    color: "#6b8e23",
    damage: 20,
    desc: "Scrappy garrison recruit wielding a gladius and scutum shield. Determined to hold the line despite worn equipment.",
    hp: 700,
    name: "Foot Soldier",
  },
  hexling: {
    attackSpeed: 880,
    canTargetFlying: true,
    color: "#c026d3",
    damage: 34,
    desc: "Flickering spirit of malice that hurls occult bolts from afar. Can strike both grounded and airborne foes.",
    hp: 1050,
    isRanged: true,
    name: "Hexling",
    range: 240,
  },
  hexseer: {
    attackSpeed: 720,
    canTargetFlying: true,
    color: "#f472b6",
    damage: 58,
    desc: "Ascendant hex caster woven from powerful souls. Its eldritch volleys reach further and hit harder than any lesser spirit.",
    hp: 1500,
    isRanged: true,
    name: "Hexseer",
    range: 290,
  },
  knight: {
    attackSpeed: 850,
    color: "#c0c0c0",
    damage: 38,
    desc: "Champion in full plate, each bearing uniquely forged armor and weaponry. The garrison's finest and most fearsome.",
    hp: 1000,
    name: "Knight",
  },
  reinforcement: {
    attackSpeed: 1000,
    color: "#a78bfa",
    damage: 30,
    desc: "Arcane warrior conjured by battlefield sorcery, each arriving in uniquely enchanted plate and helm. Grows stronger with spell upgrades.",
    hp: 1000,
    name: "Reinforcement",
  },
  rowing: {
    attackSpeed: 1000,
    color: "#8b5cf6",
    damage: 45,
    desc: "Hulking specter dragged back by a violet curse. Swings with relentless, bone-crushing force that few can withstand.",
    hp: 1700,
    name: "Hexrower",
  },
  thesis: {
    attackSpeed: 750,
    color: "#a855f7",
    damage: 55,
    desc: "Reanimated scholar bound by hex magic and forged from elite souls. Channels forbidden knowledge into devastating strikes.",
    hp: 1400,
    name: "Hexthesis",
  },
  turret: {
    attackSpeed: 800,
    color: "#f59e0b",
    damage: 35,
    desc: "Mechanical siege emplacement that rains bolts on nearby threats. Immobile but relentless once deployed.",
    hp: 800,
    isRanged: true,
    isStationary: true,
    name: "Defense Turret",
    range: 140,
  },
};
